// ─────────────────────────────────────────────────────────────────────────────
// AppLocalizations — Traductions de l'interface TontineClair
//
// Langues prioritaires : FR · EN · ES · PT · AR
// Architecture extensible : ajouter une langue = ajouter un bloc dans _translations
// Usage   : context.tr('cle')  ou  AppLocalizations.of(context).get('cle')
// Fallback : langue demandée → FR → clé brute (jamais de clé technique affichée)
// ─────────────────────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import '../services/locale_service.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Extension de commodité sur BuildContext
// ─────────────────────────────────────────────────────────────────────────────

extension AppLocalizationsExt on BuildContext {
  /// Traduit une clé dans la langue active.
  /// Fallback : langue active → français → clé brute.
  String tr(String key) => AppLocalizations.of(this).get(key);
}

// ─────────────────────────────────────────────────────────────────────────────
// Classe principale
// ─────────────────────────────────────────────────────────────────────────────

class AppLocalizations {
  final String langueCode;

  const AppLocalizations(this.langueCode);

  /// Récupère l'instance depuis le contexte (via _AppLocalizationsWrapperState).
  static AppLocalizations of(BuildContext context) {
    final service = context.findAncestorStateOfType<_AppLocalizationsWrapperState>();
    return AppLocalizations(service?.langueCode ?? 'fr');
  }

  /// Traduit une clé. Fallback : français, puis la clé elle-même.
  String get(String key) {
    final langMap = _translations[langueCode];
    if (langMap != null && langMap.containsKey(key)) return langMap[key]!;
    // Fallback français
    final frMap = _translations['fr'];
    if (frMap != null && frMap.containsKey(key)) return frMap[key]!;
    // Dernier recours : retourner la clé (ne jamais afficher null)
    return key;
  }

  // ── Raccourcis directs (IDE autocomplete) ─────────────────────────────
  String get appNom              => get('app_nom');
  String get accueil             => get('accueil');
  String get mesTontines         => get('mes_tontines');
  String get creerTontine        => get('creer_tontine');
  String get rejoindre           => get('rejoindre');
  String get tableauDeBord       => get('tableau_de_bord');
  String get cotisations         => get('cotisations');
  String get caisse              => get('caisse');
  String get prets               => get('prets');
  String get tirage              => get('tirage');
  String get votes               => get('votes');
  String get membres             => get('membres');
  String get journal             => get('journal');
  String get parametres          => get('parametres');
  String get langue              => get('langue');
  String get choisirLangue       => get('choisir_langue');
  String get enregistrer         => get('enregistrer');
  String get annuler             => get('annuler');
  String get confirmer           => get('confirmer');
  String get retour              => get('retour');
  String get erreur              => get('erreur');
  String get succes              => get('succes');
  String get chargement          => get('chargement');
  String get deconnexion         => get('deconnexion');
}

// ─────────────────────────────────────────────────────────────────────────────
// Widget wrapper — écoute LocaleService et rebuilde l'arbre au changement
// ─────────────────────────────────────────────────────────────────────────────

class AppLocalizationsWrapper extends StatefulWidget {
  final Widget child;
  final LocaleService localeService;

  const AppLocalizationsWrapper({
    super.key,
    required this.child,
    required this.localeService,
  });

  @override
  State<AppLocalizationsWrapper> createState() => _AppLocalizationsWrapperState();
}

class _AppLocalizationsWrapperState extends State<AppLocalizationsWrapper> {
  String get langueCode => widget.localeService.langue.code;

  @override
  void initState() {
    super.initState();
    widget.localeService.addListener(_onLangueChange);
  }

  @override
  void dispose() {
    widget.localeService.removeListener(_onLangueChange);
    super.dispose();
  }

  void _onLangueChange() => setState(() {});

  @override
  Widget build(BuildContext context) => widget.child;
}

// ─────────────────────────────────────────────────────────────────────────────
// Dictionnaire des traductions — 5 langues × 280+ clés
// Pour ajouter une langue : ajouter un bloc 'xx': { ... } avec toutes les clés
// ─────────────────────────────────────────────────────────────────────────────

const Map<String, Map<String, String>> _translations = {

  // ════════════════════════════════════════════════════════════════════════
  // 🇫🇷 FRANÇAIS
  // ════════════════════════════════════════════════════════════════════════
  'fr': {
    'app_nom': 'TontineClair',
    'app_slogan': 'Vos tontines, en toute transparence',
    'accueil': 'Accueil',
    'mes_tontines': 'Mes tontines',
    'creer_tontine': 'Créer une tontine',
    'rejoindre': 'Rejoindre',
    'rejoindre_tontine': 'Rejoindre une tontine',
    'tableau_de_bord': 'Tableau de bord',
    'cotisations': 'Cotisations',
    'caisse': 'Caisse',
    'prets': 'Prêts',
    'tirage': 'Tirage au sort',
    'votes': 'Votes',
    'membres': 'Membres',
    'journal': 'Journal',
    'historique': 'Historique',
    'classement': 'Classement',
    'abonnement': 'Abonnement',
    'parametres': 'Paramètres',
    'retour': 'Retour',
    'fermer': 'Fermer',
    'annuler': 'Annuler',
    'confirmer': 'Confirmer',
    'enregistrer': 'Enregistrer',
    'supprimer': 'Supprimer',
    'modifier': 'Modifier',
    'details': 'Détails',
    'partager': 'Partager',
    'appliquer': 'Appliquer',
    'reessayer': 'Réessayer',
    'rechercher': 'Rechercher',
    'nouveau': 'Nouveau',
    'oui': 'Oui',
    'non': 'Non',
    'langue': 'Langue',
    'choisir_langue': 'Choisir la langue',
    'langue_actuelle': 'Langue actuelle',
    'langue_choisie': 'Langue sélectionnée',
    'langue_modifiee': 'Langue modifiée avec succès',
    'langues_disponibles': 'Langues disponibles',
    'erreur': 'Erreur',
    'succes': 'Succès',
    'chargement': 'Chargement…',
    'bienvenue': 'Bienvenue',
    'deconnexion': 'Déconnexion',
    'connexion_requise': 'Connexion requise',
    'verifier_connexion': 'Vérifiez votre connexion internet',
    'tontine_introuvable': 'Tontine introuvable',
    'aucune_tontine': 'Aucune tontine',
    'code_tontine': 'Code de la tontine',
    'nom_tontine': 'Nom de la tontine',
    'montant': 'Montant',
    'devise': 'Devise',
    'periodicite': 'Périodicité',
    'membres_count': 'membres',
    'tour': 'Tour',
    'cycle': 'Cycle',
    'beneficiaire': 'Bénéficiaire',
    'total': 'Total',
    'solde': 'Solde',
    'caisse_solde': 'Solde de caisse',
    'paye': 'Payé',
    'non_paye': 'Non payé',
    'paiement': 'Paiement',
    'confirmer_paiement': 'Confirmer le paiement',
    'annuler_paiement': 'Annuler le paiement',
    'paiement_enregistre': 'Paiement enregistré !',
    'paiement_annule': 'Paiement annulé et journal mis à jour.',
    'methode_paiement': 'Méthode de paiement',
    'exporter_pdf': 'Exporter PDF',
    'vote_ouvert': 'Vote ouvert',
    'vote_clos': 'Vote clôturé',
    'abstention': 'Abstention',
    'ont_vote': 'ont voté',
    'voter': 'Voter',
    'vote_libre': 'Vote libre',
    'vote_binaire': 'Oui / Non',
    'vote_enregistre': 'Vote enregistré !',
    'vote_cree': 'Vote ouvert !',
    'ouvrir_vote': 'Ouvrir le vote',
    'cloture_vote': 'Clôturer le vote',
    'nouveau_vote': 'Nouveau vote',
    'chargement_votes': 'Chargement des votes…',
    'aucun_vote': 'Aucun vote en cours.',
    'question_vote': 'Question / Objet du vote',
    'type_vote': 'Type de vote',
    'question_requise': 'Question requise',
    'creer_vote': 'Créer le vote',
    'restant': 'restant',
    'verrouille': 'Verrouillé',
    'nouveau_cycle': 'Nouveau cycle',
    'cycle_termine': 'Cycle terminé',
    'demarrer_cycle': 'Démarrer le cycle',
    'proposer_nouveau_cycle': 'Proposer un nouveau cycle',
    'vote_redemarrage': 'Voir le vote de redémarrage',
    'pin': 'PIN',
    'entrer_pin': 'Entrer votre PIN',
    'pin_incorrect': 'PIN incorrect',
    'changer_pin': 'Changer mon PIN',
    'nouveau_pin': 'Nouveau PIN',
    'ancien_pin': 'Ancien PIN (provisoire)',
    'pin_gestionnaire': 'PIN gestionnaire',
    'confirmer_pin': 'Confirmer avec votre PIN',
    'pin_trop_court': 'PIN trop court.',
    'pin_attribue': 'PIN attribué',
    'gestionnaire': 'Gestionnaire',
    'membre': 'Membre',
    'ajouter_membre': 'Ajouter un membre',
    'nouveau_membre': 'Nom du nouveau membre',
    'aucun_membre': 'Aucun membre à afficher.',
    'mode_gestion': 'Mode gestion · ',
    'mode_consultation': 'Mode consultation',
    'acces_gestionnaire': 'Accès gestionnaire',
    'verrouiller': 'Verrouiller',
    'session_terminee': 'Session gestionnaire terminée.',
    'qui_es_tu': 'Mon nom',
    'choisir_nom': 'Choisir mon nom',
    'tres_fiable': 'Très fiable',
    'fiable': 'Fiable',
    'a_surveiller': 'À surveiller',
    'risque': 'Risqué',
    'tres_risque': 'Très risqué',
    'caisse_commune': 'Caisse commune',
    'solde_disponible': 'SOLDE DISPONIBLE',
    'apport': 'Apport',
    'depense': 'Dépense',
    'penalite': 'Pénalité',
    'mouvements': 'Mouvements',
    'aucun_mouvement': 'Aucun mouvement enregistré.',
    'apport_caisse': 'Apport en caisse',
    'depense_caisse': 'Dépense de caisse',
    'appliquer_penalite': 'Appliquer une pénalité',
    'membre_penalise': 'Membre pénalisé',
    'description_motif': 'Description / Motif',
    'solde_insuffisant': 'Solde insuffisant',
    'prets_internes': 'Prêts internes',
    'solde_caisse': 'Solde caisse',
    'aucun_pret': 'Aucun prêt enregistré.',
    'nouveau_pret': 'Nouveau prêt',
    'emprunteur': 'Emprunteur',
    'taux_interet': 'Taux d\'intérêt (%)',
    'duree_mois': 'Durée (mois)',
    'creer_pret': 'Créer le prêt',
    'confirmer_pret': 'Confirmer le prêt',
    'montant_prete': 'Montant prêté',
    'taux': 'Taux',
    'duree': 'Durée',
    'total_du': 'Total dû',
    'emprunte': 'Emprunté',
    'rembourse': 'Remboursé',
    'pret_cree': 'Prêt créé avec succès !',
    'données_invalides': 'Données invalides',
    'tirage_certifie': 'Tirage au sort certifié',
    'tirage_verrouille': 'Tirage verrouillé',
    'tirage_signe': 'Tirage verrouillé et signé !',
    'ordre_passage': 'Ordre de passage',
    'ordre_actuel': 'Ordre actuel',
    'beneficiaire_tour': 'Bénéficiaire du tour actuel',
    'tour_sur': 'Tour {n}/{total}',
    'deja_servi': 'Déjà servi ce cycle',
    'seul_gest_tirage': 'Seul un gestionnaire peut lancer le tirage.',
    'verrouiller_tirage': 'Verrouiller le tirage',
    'action_definitive': 'Cette action est définitive.',
    'notifications': 'Notifications',
    'rappels': 'Rappels',
    'echeance': 'Échéance',
    'retard': 'En retard',
    'dans_jours': 'dans {n} jours',
    'demain': 'Demain',
    'aujourdhui': 'Aujourd\'hui',
    'indicateurs': 'Indicateurs',
    'total_cotise': 'Total cotisé',
    'attendu': 'Attendu',
    'membres_a_jour': 'Membres à jour',
    'en_attente': 'En attente',
    'penalites': 'Pénalités',
    'prets_en_cours': 'Prêts en cours',
    'votes_ouverts': 'Votes ouverts',
    'retour_btn': 'Retour',
    'partager_recapitulatif': 'Partager le récap sur WhatsApp',
    'tontine_prete': 'La tontine est prête. Le gestionnaire doit définir l\'ordre de passage pour lancer le premier tour.',
    'tous_servis': 'Tous les membres ont été servis. Souhaitez-vous proposer un nouveau cycle ?',
    'recevra': 'Recevra',
    'prochaine_cotisation': 'Prochaine cotisation',
    'nom_groupe': 'Nom du groupe',
    'montant_cotisation': 'Montant de cotisation',
    'creer_la_tontine': 'Créer la tontine',
    'ouvrir_tontine': 'Ouvrir la tontine',
    'code_rejoindre': 'Code de la tontine',
    'entrer_code': 'Entrer le code',
    'zone_dangereuse': 'Zone dangereuse',
    'supprimer_tontine': 'Supprimer la tontine',
    'supprimer_confirm': 'Rend la tontine inaccessible à tous les membres. Le code d\'invitation est immédiatement invalidé. L\'historique reste conservé.',
    'retour_mes_tontines': 'Retour à mes tontines',
    'tontine_supprimee': 'Tontine supprimée',
    'tontine_supprimee_msg': 'Cette tontine a été supprimée par son gestionnaire et n\'est plus accessible.',
    'tous': 'Tous',
    'score': 'Score',
    'nom': 'Nom',
    'qui_etes_vous': 'Qui es-tu ?',
    'ton_pin': 'Ton PIN',
    'acceder': 'Accéder',
    'inviter_whatsapp': 'Inviter sur WhatsApp',
    'proposer_retrait': 'Proposer le retrait',
    'vote_securise_collectif': 'Vote sécurisé · Décision collective',
    'score_confiance': 'Score de confiance',
    'score_confiance_ia': 'Score de confiance IA',
    'recommandations_ia_consultatif': 'Recommandations de l\'IA (consultatif uniquement)',
    'modifier_score_manuel': 'Modifier le score manuellement',
    'reserve_admin_audit': 'Réservé aux administrateurs · Enregistré dans l\'audit',
    'nouveau_score': 'Nouveau score (0-100)',
    'motif_modification': 'Motif de la modification',
    'motif_modif_hint': 'Raison justifiant cette modification manuelle...',
    'motif_proposition': 'Motif de la proposition (obligatoire)',
    'motif_retrait_hint': 'Décrivez précisément les raisons justifiant cette proposition de retrait...',
    'quorum_minimum': 'Quorum minimum',
    'taux_participation_requis': 'Taux de participation requis',
    'majorite_requise': 'Majorité requise',
    'votes_pour_requis': 'Votes Pour requis pour adoption',
    'votre_pin_gest': 'Votre PIN gestionnaire',
    'creer_vote_retrait': 'Créer le vote de retrait',
    'conditions_vote_retrait': 'Conditions du vote de retrait',
    'recalculer': 'Recalculer',
    'tab_score_ia': 'Score & IA',
    'decisions': 'Décisions',
    'espace_admin': 'Espace administrateur',
    'cle_admin': 'Clé administrateur',
    'acceder_btn': 'Accéder',
    'cle_incorrecte': 'Clé incorrecte ou erreur réseau.',
    'demandes': 'Demandes',
    'tontines_admin': 'Tontines',
    'aucune_demande': 'Aucune demande.',
    'refuser_demande': 'Refuser la demande',
    'motif_refus': 'Motif du refus',
    'confirmer_refus': 'Confirmer le refus',
    'premium_active': 'Premium activé !',
    'premium_desactive': 'Premium désactivé.',
    'activer_premium': 'Activer Premium',
    'outils_dev': 'Outils développeur',
    'acces_reserve': 'Accès réservé — ne pas partager',
    'tester_connexion': 'Tester la connexion Supabase',
    'reconfigurer': 'Reconfigurer les credentials',
    'retirer_liste': 'Retirer de ma liste',
    'retirer_tontine_titre': 'Retirer de la liste ?',
    'retirer_tontine_msg': 'Voulez-vous retirer cette tontine de votre liste locale ?\nLa tontine reste accessible avec son code.',
    'code_label': 'Code : ',
    'espace_administrateur': 'Espace administrateur',
    'slogan_accueil': 'Chaque cotisation est en ligne. Tout le monde voit la même chose, en direct.',
    'titre_accueil': 'Mes tontines',
    'tontine_sans_dispute': 'La tontine sans dispute',
    'tontine_description': 'Crée une tontine et partage son code, ou rejoins celle de ton groupe pour tout suivre en direct.',
    'diagnostic_connexion': 'Diagnostic connexion',
    'retester': 'Retester',
    'test_en_cours': 'Test en cours…',
    'devises_associees': 'Devises associées',
    'chargement_cotisations': 'Chargement des cotisations…',
    'relancer_retardataires': 'Relancer tous les retardataires',
    'ignorer': 'Ignorer',
    'envoyer_pin_whatsapp': 'Envoyer le PIN par WhatsApp',
    'communication_pin': 'Communiquer ce PIN au membre pour qu\'il le change.',
    'pin_provisoire': 'PIN provisoire',
    'reinitialiser_pin': 'Réinitialiser le PIN',
    'generer_pin': 'Générer et attribuer le PIN',
    'mois': 'mois',
    'cycles': 'cycles',
    'chargement_dashboard': 'Chargement du dashboard…',
    'donnees_temps_reel': 'Données en temps réel depuis Supabase',
    'aucune_donnee': 'Aucune donnée disponible',
    'aucune_alerte': 'Aucune alerte active',
    'actif': 'Actifs',
    'expire': 'Expirés',
    'en_attente_statut': 'En attente',
    'mensuel': 'Mensuel',
    'annuel': 'Annuel',
    'suivi_abonnements': 'Suivi des abonnements',
    'montant_total_actif': 'Montant total actif',
    'estime_ce_mois': 'Estimé ce mois',
    'retirer': 'Retirer',
    'mode_paiement_label': 'Mode de paiement',
    'mois_label': '{n} mois',
    'tour_n': 'N° {n}',
    'echéance_depassee': 'Échéance dépassée ({n} j)',
    'jours_restants': 'Jours restants',
    'membres_modules': 'Modules',
    'reponse_copiee': 'Réponse copiée',
    'whatsapp_indisponible': 'WhatsApp non disponible.',
    'erreur_export_pdf': 'Erreur export PDF : ',
    'erreur_whatsapp': 'Impossible d\'ouvrir WhatsApp.',
    'donnees_incompletes': 'Données incomplètes',
    'identifiant_vote_manquant': 'Erreur : identifiant du vote manquant. Rechargez la tontine.',
    'deja_vote': 'Vous avez déjà voté.',
    'pin_gestionnaire_incorrect': 'PIN gestionnaire incorrect. Réessayez.',
    'confirmer_vote': 'Confirmer ton vote',
    'pin_membre': 'Ton PIN membre',
    'pin_de': 'PIN de ',
    'ton_vote': 'Ton vote',
    'ton_pin_vote': 'Ton PIN de vote',
    'oui_non_abstention': 'Oui / Non / Abstention',
    'erreur_inconnue': 'Erreur inconnue.',
    'rechargez_page': 'Aucun membre disponible. Rechargez la page.',
    'erreur_pdf': 'Erreur PDF : ',
  },

  // ════════════════════════════════════════════════════════════════════════
  // 🇬🇧 ENGLISH
  // ════════════════════════════════════════════════════════════════════════
  'en': {
    'app_nom': 'TontineClair',
    'app_slogan': 'Your tontines, with full transparency',
    'accueil': 'Home',
    'mes_tontines': 'My tontines',
    'creer_tontine': 'Create a tontine',
    'rejoindre': 'Join',
    'rejoindre_tontine': 'Join a tontine',
    'tableau_de_bord': 'Dashboard',
    'cotisations': 'Contributions',
    'caisse': 'Treasury',
    'prets': 'Loans',
    'tirage': 'Draw',
    'votes': 'Votes',
    'membres': 'Members',
    'journal': 'Journal',
    'historique': 'History',
    'classement': 'Rankings',
    'abonnement': 'Subscription',
    'parametres': 'Settings',
    'retour': 'Back',
    'fermer': 'Close',
    'annuler': 'Cancel',
    'confirmer': 'Confirm',
    'enregistrer': 'Save',
    'supprimer': 'Delete',
    'modifier': 'Edit',
    'details': 'Details',
    'partager': 'Share',
    'appliquer': 'Apply',
    'reessayer': 'Retry',
    'rechercher': 'Search',
    'nouveau': 'New',
    'oui': 'Yes',
    'non': 'No',
    'langue': 'Language',
    'choisir_langue': 'Choose language',
    'langue_actuelle': 'Current language',
    'langue_choisie': 'Selected language',
    'langue_modifiee': 'Language changed successfully',
    'langues_disponibles': 'Available languages',
    'erreur': 'Error',
    'succes': 'Success',
    'chargement': 'Loading…',
    'bienvenue': 'Welcome',
    'deconnexion': 'Log out',
    'connexion_requise': 'Connection required',
    'verifier_connexion': 'Check your internet connection',
    'tontine_introuvable': 'Tontine not found',
    'aucune_tontine': 'No tontines',
    'code_tontine': 'Tontine code',
    'nom_tontine': 'Tontine name',
    'montant': 'Amount',
    'devise': 'Currency',
    'periodicite': 'Frequency',
    'membres_count': 'members',
    'tour': 'Round',
    'cycle': 'Cycle',
    'beneficiaire': 'Beneficiary',
    'total': 'Total',
    'solde': 'Balance',
    'caisse_solde': 'Treasury balance',
    'paye': 'Paid',
    'non_paye': 'Unpaid',
    'paiement': 'Payment',
    'confirmer_paiement': 'Confirm payment',
    'annuler_paiement': 'Cancel payment',
    'paiement_enregistre': 'Payment recorded!',
    'paiement_annule': 'Payment cancelled and journal updated.',
    'methode_paiement': 'Payment method',
    'exporter_pdf': 'Export PDF',
    'vote_ouvert': 'Open vote',
    'vote_clos': 'Closed vote',
    'abstention': 'Abstain',
    'ont_vote': 'have voted',
    'voter': 'Vote',
    'vote_libre': 'Free vote',
    'vote_binaire': 'Yes / No',
    'vote_enregistre': 'Vote recorded!',
    'vote_cree': 'Vote opened!',
    'ouvrir_vote': 'Open vote',
    'cloture_vote': 'Close vote',
    'nouveau_vote': 'New vote',
    'chargement_votes': 'Loading votes…',
    'aucun_vote': 'No active votes.',
    'question_vote': 'Question / Subject',
    'type_vote': 'Vote type',
    'question_requise': 'Question required',
    'creer_vote': 'Create vote',
    'restant': 'remaining',
    'verrouille': 'Locked',
    'nouveau_cycle': 'New cycle',
    'cycle_termine': 'Cycle complete',
    'demarrer_cycle': 'Start cycle',
    'proposer_nouveau_cycle': 'Propose a new cycle',
    'vote_redemarrage': 'See restart vote',
    'pin': 'PIN',
    'entrer_pin': 'Enter your PIN',
    'pin_incorrect': 'Incorrect PIN',
    'changer_pin': 'Change my PIN',
    'nouveau_pin': 'New PIN',
    'ancien_pin': 'Old PIN (provisional)',
    'pin_gestionnaire': 'Manager PIN',
    'confirmer_pin': 'Confirm with your PIN',
    'pin_trop_court': 'PIN too short.',
    'pin_attribue': 'PIN assigned',
    'gestionnaire': 'Manager',
    'membre': 'Member',
    'ajouter_membre': 'Add member',
    'nouveau_membre': 'New member name',
    'aucun_membre': 'No members to display.',
    'mode_gestion': 'Management mode · ',
    'mode_consultation': 'Consultation mode',
    'acces_gestionnaire': 'Manager access',
    'verrouiller': 'Lock',
    'session_terminee': 'Manager session ended.',
    'qui_es_tu': 'My name',
    'choisir_nom': 'Choose my name',
    'tres_fiable': 'Very reliable',
    'fiable': 'Reliable',
    'a_surveiller': 'Watch',
    'risque': 'Risky',
    'tres_risque': 'Very risky',
    'caisse_commune': 'Common treasury',
    'solde_disponible': 'AVAILABLE BALANCE',
    'apport': 'Contribution',
    'depense': 'Expense',
    'penalite': 'Penalty',
    'mouvements': 'Transactions',
    'aucun_mouvement': 'No transactions recorded.',
    'apport_caisse': 'Treasury contribution',
    'depense_caisse': 'Treasury expense',
    'appliquer_penalite': 'Apply a penalty',
    'membre_penalise': 'Penalized member',
    'description_motif': 'Description / Reason',
    'solde_insuffisant': 'Insufficient balance',
    'prets_internes': 'Internal loans',
    'solde_caisse': 'Treasury balance',
    'aucun_pret': 'No loans recorded.',
    'nouveau_pret': 'New loan',
    'emprunteur': 'Borrower',
    'taux_interet': 'Interest rate (%)',
    'duree_mois': 'Duration (months)',
    'creer_pret': 'Create loan',
    'confirmer_pret': 'Confirm loan',
    'montant_prete': 'Loaned amount',
    'taux': 'Rate',
    'duree': 'Duration',
    'total_du': 'Total owed',
    'emprunte': 'Borrowed',
    'rembourse': 'Repaid',
    'pret_cree': 'Loan created successfully!',
    'données_invalides': 'Invalid data',
    'tirage_certifie': 'Certified draw',
    'tirage_verrouille': 'Draw locked',
    'tirage_signe': 'Draw locked and signed!',
    'ordre_passage': 'Order of passage',
    'ordre_actuel': 'Current order',
    'beneficiaire_tour': 'Current round beneficiary',
    'tour_sur': 'Round {n}/{total}',
    'deja_servi': 'Already served this cycle',
    'seul_gest_tirage': 'Only a manager can launch the draw.',
    'verrouiller_tirage': 'Lock the draw',
    'action_definitive': 'This action is permanent.',
    'notifications': 'Notifications',
    'rappels': 'Reminders',
    'echeance': 'Due date',
    'retard': 'Overdue',
    'dans_jours': 'in {n} days',
    'demain': 'Tomorrow',
    'aujourdhui': 'Today',
    'indicateurs': 'Indicators',
    'total_cotise': 'Total contributed',
    'attendu': 'Expected',
    'membres_a_jour': 'Up-to-date members',
    'en_attente': 'Pending',
    'penalites': 'Penalties',
    'prets_en_cours': 'Active loans',
    'votes_ouverts': 'Open votes',
    'retour_btn': 'Back',
    'partager_recapitulatif': 'Share summary on WhatsApp',
    'tontine_prete': 'The tontine is ready. The manager must define the order to start the first round.',
    'tous_servis': 'All members have been served. Would you like to propose a new cycle?',
    'recevra': 'Will receive',
    'prochaine_cotisation': 'Next contribution',
    'nom_groupe': 'Group name',
    'montant_cotisation': 'Contribution amount',
    'creer_la_tontine': 'Create tontine',
    'ouvrir_tontine': 'Open tontine',
    'code_rejoindre': 'Tontine code',
    'entrer_code': 'Enter code',
    'zone_dangereuse': 'Danger zone',
    'supprimer_tontine': 'Delete tontine',
    'supprimer_confirm': 'Makes the tontine inaccessible to all members. The invitation code is immediately invalidated. History is preserved.',
    'retour_mes_tontines': 'Back to my tontines',
    'tontine_supprimee': 'Tontine deleted',
    'tontine_supprimee_msg': 'This tontine has been deleted by its manager and is no longer accessible.',
    'tous': 'All',
    'score': 'Score',
    'nom': 'Name',
    'qui_etes_vous': 'Who are you?',
    'ton_pin': 'Your PIN',
    'acceder': 'Access',
    'inviter_whatsapp': 'Invite on WhatsApp',
    'proposer_retrait': 'Propose removal',
    'vote_securise_collectif': 'Secured vote · Collective decision',
    'score_confiance': 'Trust score',
    'score_confiance_ia': 'AI Trust score',
    'recommandations_ia_consultatif': 'AI recommendations (advisory only)',
    'modifier_score_manuel': 'Edit score manually',
    'reserve_admin_audit': 'Admin only · Logged in audit trail',
    'nouveau_score': 'New score (0-100)',
    'motif_modification': 'Reason for change',
    'motif_modif_hint': 'Reason justifying this manual change...',
    'motif_proposition': 'Reason for proposal (required)',
    'motif_retrait_hint': 'Describe precisely the reasons justifying this removal proposal...',
    'quorum_minimum': 'Minimum quorum',
    'taux_participation_requis': 'Required participation rate',
    'majorite_requise': 'Required majority',
    'votes_pour_requis': 'Yes votes required for adoption',
    'votre_pin_gest': 'Your manager PIN',
    'creer_vote_retrait': 'Create removal vote',
    'conditions_vote_retrait': 'Removal vote conditions',
    'recalculer': 'Recalculate',
    'tab_score_ia': 'Score & AI',
    'decisions': 'Decisions',
    'espace_admin': 'Admin panel',
    'cle_admin': 'Admin key',
    'acceder_btn': 'Access',
    'cle_incorrecte': 'Incorrect key or network error.',
    'demandes': 'Requests',
    'tontines_admin': 'Tontines',
    'aucune_demande': 'No requests.',
    'refuser_demande': 'Refuse request',
    'motif_refus': 'Reason for refusal',
    'confirmer_refus': 'Confirm refusal',
    'premium_active': 'Premium activated!',
    'premium_desactive': 'Premium deactivated.',
    'activer_premium': 'Activate Premium',
    'outils_dev': 'Developer tools',
    'acces_reserve': 'Reserved access — do not share',
    'tester_connexion': 'Test Supabase connection',
    'reconfigurer': 'Reconfigure credentials',
    'retirer_liste': 'Remove from my list',
    'retirer_tontine_titre': 'Remove from list?',
    'retirer_tontine_msg': 'Do you want to remove this tontine from your local list?\nThe tontine remains accessible with its code.',
    'code_label': 'Code: ',
    'espace_administrateur': 'Admin panel',
    'slogan_accueil': 'Every contribution is online. Everyone sees the same thing, live.',
    'titre_accueil': 'My tontines',
    'tontine_sans_dispute': 'The dispute-free tontine',
    'tontine_description': 'Create a tontine and share its code, or join your group\'s to track everything live.',
    'diagnostic_connexion': 'Connection diagnostic',
    'retester': 'Retest',
    'test_en_cours': 'Test in progress…',
    'devises_associees': 'Associated currencies',
    'chargement_cotisations': 'Loading contributions…',
    'relancer_retardataires': 'Remind all late members',
    'ignorer': 'Dismiss',
    'envoyer_pin_whatsapp': 'Send PIN via WhatsApp',
    'communication_pin': 'Share this PIN with the member so they can change it.',
    'pin_provisoire': 'Provisional PIN',
    'reinitialiser_pin': 'Reset PIN',
    'generer_pin': 'Generate and assign PIN',
    'mois': 'months',
    'cycles': 'cycles',
    'chargement_dashboard': 'Loading dashboard…',
    'donnees_temps_reel': 'Real-time data from Supabase',
    'aucune_donnee': 'No data available',
    'aucune_alerte': 'No active alerts',
    'actif': 'Active',
    'expire': 'Expired',
    'en_attente_statut': 'Pending',
    'mensuel': 'Monthly',
    'annuel': 'Annual',
    'suivi_abonnements': 'Subscription tracking',
    'montant_total_actif': 'Total active amount',
    'estime_ce_mois': 'Estimated this month',
    'retirer': 'Remove',
    'mode_paiement_label': 'Payment method',
    'mois_label': '{n} months',
    'tour_n': 'No. {n}',
    'echéance_depassee': 'Overdue ({n} d)',
    'jours_restants': 'Days remaining',
    'membres_modules': 'Modules',
    'reponse_copiee': 'Response copied',
    'whatsapp_indisponible': 'WhatsApp not available.',
    'erreur_export_pdf': 'PDF export error: ',
    'erreur_whatsapp': 'Unable to open WhatsApp.',
    'donnees_incompletes': 'Incomplete data',
    'identifiant_vote_manquant': 'Error: vote identifier missing. Reload the tontine.',
    'deja_vote': 'You have already voted.',
    'pin_gestionnaire_incorrect': 'Incorrect manager PIN. Try again.',
    'confirmer_vote': 'Confirm your vote',
    'pin_membre': 'Your member PIN',
    'pin_de': 'PIN for ',
    'ton_vote': 'Your vote',
    'ton_pin_vote': 'Your vote PIN',
    'oui_non_abstention': 'Yes / No / Abstain',
    'erreur_inconnue': 'Unknown error.',
    'rechargez_page': 'No members available. Reload the page.',
    'erreur_pdf': 'PDF error: ',
  },

  // ════════════════════════════════════════════════════════════════════════
  // 🇪🇸 ESPAÑOL
  // ════════════════════════════════════════════════════════════════════════
  'es': {
    'app_nom': 'TontineClair',
    'app_slogan': 'Tus tontinas con total transparencia',
    'accueil': 'Inicio',
    'mes_tontines': 'Mis tontinas',
    'creer_tontine': 'Crear tontina',
    'rejoindre': 'Unirse',
    'rejoindre_tontine': 'Unirse a una tontina',
    'tableau_de_bord': 'Panel',
    'cotisations': 'Cuotas',
    'caisse': 'Caja',
    'prets': 'Préstamos',
    'tirage': 'Sorteo',
    'votes': 'Votos',
    'membres': 'Miembros',
    'journal': 'Diario',
    'historique': 'Historial',
    'classement': 'Clasificación',
    'abonnement': 'Suscripción',
    'parametres': 'Ajustes',
    'retour': 'Volver',
    'fermer': 'Cerrar',
    'annuler': 'Cancelar',
    'confirmer': 'Confirmar',
    'enregistrer': 'Guardar',
    'supprimer': 'Eliminar',
    'modifier': 'Editar',
    'details': 'Detalles',
    'partager': 'Compartir',
    'appliquer': 'Aplicar',
    'reessayer': 'Reintentar',
    'rechercher': 'Buscar',
    'nouveau': 'Nuevo',
    'oui': 'Sí',
    'non': 'No',
    'langue': 'Idioma',
    'choisir_langue': 'Elegir idioma',
    'langue_actuelle': 'Idioma actual',
    'langue_choisie': 'Idioma seleccionado',
    'langue_modifiee': 'Idioma cambiado correctamente',
    'langues_disponibles': 'Idiomas disponibles',
    'erreur': 'Error',
    'succes': 'Éxito',
    'chargement': 'Cargando…',
    'bienvenue': 'Bienvenido',
    'deconnexion': 'Cerrar sesión',
    'connexion_requise': 'Conexión requerida',
    'verifier_connexion': 'Verifica tu conexión a internet',
    'tontine_introuvable': 'Tontina no encontrada',
    'aucune_tontine': 'Sin tontinas',
    'code_tontine': 'Código de tontina',
    'nom_tontine': 'Nombre de la tontina',
    'montant': 'Monto',
    'devise': 'Divisa',
    'periodicite': 'Periodicidad',
    'membres_count': 'miembros',
    'tour': 'Ronda',
    'cycle': 'Ciclo',
    'beneficiaire': 'Beneficiario',
    'total': 'Total',
    'solde': 'Saldo',
    'caisse_solde': 'Saldo de caja',
    'paye': 'Pagado',
    'non_paye': 'No pagado',
    'paiement': 'Pago',
    'confirmer_paiement': 'Confirmar pago',
    'annuler_paiement': 'Cancelar pago',
    'paiement_enregistre': '¡Pago registrado!',
    'paiement_annule': 'Pago cancelado y diario actualizado.',
    'methode_paiement': 'Método de pago',
    'exporter_pdf': 'Exportar PDF',
    'vote_ouvert': 'Votación abierta',
    'vote_clos': 'Votación cerrada',
    'abstention': 'Abstención',
    'ont_vote': 'han votado',
    'voter': 'Votar',
    'vote_libre': 'Voto libre',
    'vote_binaire': 'Sí / No',
    'vote_enregistre': '¡Voto registrado!',
    'vote_cree': '¡Votación abierta!',
    'ouvrir_vote': 'Abrir votación',
    'cloture_vote': 'Cerrar votación',
    'nouveau_vote': 'Nueva votación',
    'chargement_votes': 'Cargando votos…',
    'aucun_vote': 'Ninguna votación activa.',
    'question_vote': 'Pregunta / Objeto de la votación',
    'type_vote': 'Tipo de votación',
    'question_requise': 'Pregunta requerida',
    'creer_vote': 'Crear votación',
    'restant': 'restante',
    'verrouille': 'Bloqueado',
    'nouveau_cycle': 'Nuevo ciclo',
    'cycle_termine': 'Ciclo completado',
    'demarrer_cycle': 'Iniciar ciclo',
    'proposer_nouveau_cycle': 'Proponer un nuevo ciclo',
    'vote_redemarrage': 'Ver votación de reinicio',
    'pin': 'PIN',
    'entrer_pin': 'Ingresa tu PIN',
    'pin_incorrect': 'PIN incorrecto',
    'changer_pin': 'Cambiar mi PIN',
    'nouveau_pin': 'Nuevo PIN',
    'ancien_pin': 'PIN anterior (provisional)',
    'pin_gestionnaire': 'PIN del gestor',
    'confirmer_pin': 'Confirmar con tu PIN',
    'pin_trop_court': 'PIN demasiado corto.',
    'pin_attribue': 'PIN asignado',
    'gestionnaire': 'Gestor',
    'membre': 'Miembro',
    'ajouter_membre': 'Agregar miembro',
    'nouveau_membre': 'Nombre del nuevo miembro',
    'aucun_membre': 'No hay miembros para mostrar.',
    'mode_gestion': 'Modo gestión · ',
    'mode_consultation': 'Modo consulta',
    'acces_gestionnaire': 'Acceso gestor',
    'verrouiller': 'Bloquear',
    'session_terminee': 'Sesión del gestor terminada.',
    'qui_es_tu': 'Mi nombre',
    'choisir_nom': 'Elegir mi nombre',
    'tres_fiable': 'Muy fiable',
    'fiable': 'Fiable',
    'a_surveiller': 'Vigilar',
    'risque': 'Arriesgado',
    'tres_risque': 'Muy arriesgado',
    'caisse_commune': 'Caja común',
    'solde_disponible': 'SALDO DISPONIBLE',
    'apport': 'Aportación',
    'depense': 'Gasto',
    'penalite': 'Penalización',
    'mouvements': 'Movimientos',
    'aucun_mouvement': 'Ningún movimiento registrado.',
    'apport_caisse': 'Aportación a la caja',
    'depense_caisse': 'Gasto de la caja',
    'appliquer_penalite': 'Aplicar penalización',
    'membre_penalise': 'Miembro penalizado',
    'description_motif': 'Descripción / Motivo',
    'solde_insuffisant': 'Saldo insuficiente',
    'prets_internes': 'Préstamos internos',
    'solde_caisse': 'Saldo de caja',
    'aucun_pret': 'Ningún préstamo registrado.',
    'nouveau_pret': 'Nuevo préstamo',
    'emprunteur': 'Prestatario',
    'taux_interet': 'Tasa de interés (%)',
    'duree_mois': 'Duración (meses)',
    'creer_pret': 'Crear préstamo',
    'confirmer_pret': 'Confirmar préstamo',
    'montant_prete': 'Monto prestado',
    'taux': 'Tasa',
    'duree': 'Duración',
    'total_du': 'Total adeudado',
    'emprunte': 'Prestado',
    'rembourse': 'Reembolsado',
    'pret_cree': '¡Préstamo creado con éxito!',
    'données_invalides': 'Datos no válidos',
    'tirage_certifie': 'Sorteo certificado',
    'tirage_verrouille': 'Sorteo bloqueado',
    'tirage_signe': '¡Sorteo bloqueado y firmado!',
    'ordre_passage': 'Orden de paso',
    'ordre_actuel': 'Orden actual',
    'beneficiaire_tour': 'Beneficiario de la ronda actual',
    'tour_sur': 'Ronda {n}/{total}',
    'deja_servi': 'Ya atendido este ciclo',
    'seul_gest_tirage': 'Solo un gestor puede lanzar el sorteo.',
    'verrouiller_tirage': 'Bloquear el sorteo',
    'action_definitive': 'Esta acción es definitiva.',
    'notifications': 'Notificaciones',
    'rappels': 'Recordatorios',
    'echeance': 'Vencimiento',
    'retard': 'Atrasado',
    'dans_jours': 'en {n} días',
    'demain': 'Mañana',
    'aujourdhui': 'Hoy',
    'indicateurs': 'Indicadores',
    'total_cotise': 'Total aportado',
    'attendu': 'Esperado',
    'membres_a_jour': 'Miembros al día',
    'en_attente': 'Pendiente',
    'penalites': 'Penalizaciones',
    'prets_en_cours': 'Préstamos activos',
    'votes_ouverts': 'Votaciones abiertas',
    'retour_btn': 'Volver',
    'partager_recapitulatif': 'Compartir resumen por WhatsApp',
    'tontine_prete': 'La tontina está lista. El gestor debe definir el orden para iniciar la primera ronda.',
    'tous_servis': '¿Todos los miembros han sido atendidos. ¿Desea proponer un nuevo ciclo?',
    'recevra': 'Recibirá',
    'prochaine_cotisation': 'Próxima cuota',
    'nom_groupe': 'Nombre del grupo',
    'montant_cotisation': 'Monto de la cuota',
    'creer_la_tontine': 'Crear tontina',
    'ouvrir_tontine': 'Abrir tontina',
    'code_rejoindre': 'Código de tontina',
    'entrer_code': 'Ingresar código',
    'zone_dangereuse': 'Zona peligrosa',
    'supprimer_tontine': 'Eliminar tontina',
    'supprimer_confirm': 'Hace la tontina inaccesible para todos los miembros. El código de invitación se invalida inmediatamente. El historial se conserva.',
    'retour_mes_tontines': 'Volver a mis tontinas',
    'tontine_supprimee': 'Tontina eliminada',
    'tontine_supprimee_msg': 'Esta tontina ha sido eliminada por su gestor y ya no es accesible.',
    'tous': 'Todos',
    'score': 'Puntuación',
    'nom': 'Nombre',
    'qui_etes_vous': '¿Quién eres?',
    'ton_pin': 'Tu PIN',
    'acceder': 'Acceder',
    'invitar_whatsapp': 'Invitar por WhatsApp',
    'inviter_whatsapp': 'Invitar por WhatsApp',
    'proposer_retrait': 'Proponer retiro',
    'vote_securise_collectif': 'Voto seguro · Decisión colectiva',
    'score_confiance': 'Puntuación de confianza',
    'score_confiance_ia': 'Puntuación de confianza IA',
    'recommandations_ia_consultatif': 'Recomendaciones de IA (solo consultivo)',
    'modifier_score_manuel': 'Editar puntuación manualmente',
    'reserve_admin_audit': 'Solo administradores · Registrado en auditoría',
    'nouveau_score': 'Nueva puntuación (0-100)',
    'motif_modification': 'Motivo de la modificación',
    'motif_modif_hint': 'Razón que justifica esta modificación manual...',
    'motif_proposition': 'Motivo de la propuesta (obligatorio)',
    'motif_retrait_hint': 'Describa con precisión las razones que justifican esta propuesta de retirada...',
    'quorum_minimum': 'Quórum mínimo',
    'taux_participation_requis': 'Tasa de participación requerida',
    'majorite_requise': 'Mayoría requerida',
    'votes_pour_requis': 'Votos Sí requeridos para adopción',
    'votre_pin_gest': 'Su PIN de gestor',
    'creer_vote_retrait': 'Crear voto de retirada',
    'conditions_vote_retrait': 'Condiciones del voto de retirada',
    'recalculer': 'Recalcular',
    'tab_score_ia': 'Puntuación & IA',
    'decisions': 'Decisiones',
    'espace_admin': 'Panel de administración',
    'cle_admin': 'Clave de administrador',
    'acceder_btn': 'Acceder',
    'cle_incorrecte': 'Clave incorrecta o error de red.',
    'demandes': 'Solicitudes',
    'tontines_admin': 'Tontinas',
    'aucune_demande': 'Sin solicitudes.',
    'refuser_demande': 'Rechazar solicitud',
    'motif_refus': 'Motivo del rechazo',
    'confirmer_refus': 'Confirmar rechazo',
    'premium_active': '¡Premium activado!',
    'premium_desactive': 'Premium desactivado.',
    'activer_premium': 'Activar Premium',
    'outils_dev': 'Herramientas de desarrollo',
    'acces_reserve': 'Acceso reservado — no compartir',
    'tester_connexion': 'Probar conexión Supabase',
    'reconfigurer': 'Reconfigurar credenciales',
    'retirer_liste': 'Quitar de mi lista',
    'retirer_tontine_titre': '¿Quitar de la lista?',
    'retirer_tontine_msg': '¿Deseas quitar esta tontina de tu lista local?\nLa tontina sigue accesible con su código.',
    'code_label': 'Código: ',
    'espace_administrateur': 'Panel de administración',
    'slogan_accueil': 'Cada cuota está en línea. Todos ven lo mismo, en vivo.',
    'titre_accueil': 'Mis tontinas',
    'tontine_sans_dispute': 'La tontina sin conflictos',
    'tontine_description': 'Crea una tontina y comparte su código, o únete a la de tu grupo para seguirlo todo en vivo.',
    'diagnostic_connexion': 'Diagnóstico de conexión',
    'retester': 'Volver a probar',
    'test_en_cours': 'Prueba en curso…',
    'devises_associees': 'Divisas asociadas',
    'chargement_cotisations': 'Cargando cuotas…',
    'relancer_retardataires': 'Recordar a todos los atrasados',
    'ignorer': 'Ignorar',
    'envoyer_pin_whatsapp': 'Enviar PIN por WhatsApp',
    'communication_pin': 'Comunica este PIN al miembro para que lo cambie.',
    'pin_provisoire': 'PIN provisional',
    'reinitialiser_pin': 'Restablecer PIN',
    'generar_pin': 'Generar y asignar PIN',
    'generer_pin': 'Generar y asignar PIN',
    'mois': 'meses',
    'cycles': 'ciclos',
    'chargement_dashboard': 'Cargando panel…',
    'donnees_temps_reel': 'Datos en tiempo real desde Supabase',
    'aucune_donnee': 'Sin datos disponibles',
    'aucune_alerte': 'Sin alertas activas',
    'actif': 'Activos',
    'expire': 'Expirados',
    'en_attente_statut': 'Pendiente',
    'mensuel': 'Mensual',
    'annuel': 'Anual',
    'suivi_abonnements': 'Seguimiento de suscripciones',
    'montant_total_actif': 'Monto total activo',
    'estime_ce_mois': 'Estimado este mes',
    'retirer': 'Quitar',
    'mode_paiement_label': 'Método de pago',
    'mois_label': '{n} meses',
    'tour_n': 'N.° {n}',
    'echéance_depassee': 'Vencido ({n} d)',
    'jours_restants': 'Días restantes',
    'membres_modules': 'Módulos',
    'reponse_copiee': 'Respuesta copiada',
    'whatsapp_indisponible': 'WhatsApp no disponible.',
    'erreur_export_pdf': 'Error al exportar PDF: ',
    'erreur_whatsapp': 'No se puede abrir WhatsApp.',
    'donnees_incompletes': 'Datos incompletos',
    'identifiant_vote_manquant': 'Error: identificador de voto faltante. Recarga la tontina.',
    'deja_vote': 'Ya has votado.',
    'pin_gestionnaire_incorrect': 'PIN del gestor incorrecto. Inténtalo de nuevo.',
    'confirmer_vote': 'Confirmar tu voto',
    'pin_membre': 'Tu PIN de miembro',
    'pin_de': 'PIN de ',
    'ton_vote': 'Tu voto',
    'ton_pin_vote': 'Tu PIN de voto',
    'oui_non_abstention': 'Sí / No / Abstención',
    'erreur_inconnue': 'Error desconocido.',
    'rechargez_page': 'Sin miembros disponibles. Recarga la página.',
    'erreur_pdf': 'Error PDF: ',
  },

  // ════════════════════════════════════════════════════════════════════════
  // 🇧🇷 PORTUGUÊS
  // ════════════════════════════════════════════════════════════════════════
  'pt': {
    'app_nom': 'TontineClair',
    'app_slogan': 'Suas tontinas com total transparência',
    'accueil': 'Início',
    'mes_tontines': 'Minhas tontinas',
    'creer_tontine': 'Criar tontina',
    'rejoindre': 'Entrar',
    'rejoindre_tontine': 'Entrar em uma tontina',
    'tableau_de_bord': 'Painel',
    'cotisations': 'Contribuições',
    'caisse': 'Caixa',
    'prets': 'Empréstimos',
    'tirage': 'Sorteio',
    'votes': 'Votos',
    'membres': 'Membros',
    'journal': 'Diário',
    'historique': 'Histórico',
    'classement': 'Classificação',
    'abonnement': 'Assinatura',
    'parametres': 'Configurações',
    'retour': 'Voltar',
    'fermer': 'Fechar',
    'annuler': 'Cancelar',
    'confirmer': 'Confirmar',
    'enregistrer': 'Salvar',
    'supprimer': 'Excluir',
    'modifier': 'Editar',
    'details': 'Detalhes',
    'partager': 'Compartilhar',
    'appliquer': 'Aplicar',
    'reessayer': 'Tentar novamente',
    'rechercher': 'Pesquisar',
    'nouveau': 'Novo',
    'oui': 'Sim',
    'non': 'Não',
    'langue': 'Idioma',
    'choisir_langue': 'Escolher idioma',
    'langue_actuelle': 'Idioma atual',
    'langue_choisie': 'Idioma selecionado',
    'langue_modifiee': 'Idioma alterado com sucesso',
    'langues_disponibles': 'Idiomas disponíveis',
    'erreur': 'Erro',
    'succes': 'Sucesso',
    'chargement': 'Carregando…',
    'bienvenue': 'Bem-vindo',
    'deconnexion': 'Sair',
    'connexion_requise': 'Conexão necessária',
    'verifier_connexion': 'Verifique sua conexão com a internet',
    'tontine_introuvable': 'Tontina não encontrada',
    'aucune_tontine': 'Nenhuma tontina',
    'code_tontine': 'Código da tontina',
    'nom_tontine': 'Nome da tontina',
    'montant': 'Valor',
    'devise': 'Moeda',
    'periodicite': 'Periodicidade',
    'membres_count': 'membros',
    'tour': 'Rodada',
    'cycle': 'Ciclo',
    'beneficiaire': 'Beneficiário',
    'total': 'Total',
    'solde': 'Saldo',
    'caisse_solde': 'Saldo do caixa',
    'paye': 'Pago',
    'non_paye': 'Não pago',
    'paiement': 'Pagamento',
    'confirmer_paiement': 'Confirmar pagamento',
    'annuler_paiement': 'Cancelar pagamento',
    'paiement_enregistre': 'Pagamento registrado!',
    'paiement_annule': 'Pagamento cancelado e diário atualizado.',
    'methode_paiement': 'Método de pagamento',
    'exporter_pdf': 'Exportar PDF',
    'vote_ouvert': 'Votação aberta',
    'vote_clos': 'Votação encerrada',
    'abstention': 'Abstenção',
    'ont_vote': 'votaram',
    'voter': 'Votar',
    'vote_livre': 'Voto livre',
    'vote_binaire': 'Sim / Não',
    'vote_enregistre': 'Voto registrado!',
    'vote_cree': 'Votação aberta!',
    'ouvrir_vote': 'Abrir votação',
    'cloture_vote': 'Encerrar votação',
    'nouveau_vote': 'Nova votação',
    'chargement_votes': 'Carregando votos…',
    'aucun_vote': 'Nenhuma votação ativa.',
    'question_vote': 'Pergunta / Objeto da votação',
    'type_vote': 'Tipo de votação',
    'question_requise': 'Pergunta necessária',
    'creer_vote': 'Criar votação',
    'restant': 'restante',
    'verrouille': 'Bloqueado',
    'nouveau_cycle': 'Novo ciclo',
    'cycle_termine': 'Ciclo concluído',
    'demarrer_cycle': 'Iniciar ciclo',
    'proposer_nouveau_cycle': 'Propor um novo ciclo',
    'vote_redemarrage': 'Ver votação de reinício',
    'pin': 'PIN',
    'entrer_pin': 'Insira seu PIN',
    'pin_incorrect': 'PIN incorreto',
    'changer_pin': 'Alterar meu PIN',
    'nouveau_pin': 'Novo PIN',
    'ancien_pin': 'PIN anterior (provisório)',
    'pin_gestionnaire': 'PIN do gestor',
    'confirmer_pin': 'Confirmar com seu PIN',
    'pin_trop_court': 'PIN muito curto.',
    'pin_attribue': 'PIN atribuído',
    'gestionnaire': 'Gestor',
    'membre': 'Membro',
    'ajouter_membre': 'Adicionar membro',
    'nouveau_membre': 'Nome do novo membro',
    'aucun_membre': 'Nenhum membro para exibir.',
    'mode_gestion': 'Modo gestão · ',
    'mode_consultation': 'Modo consulta',
    'acces_gestionnaire': 'Acesso ao gestor',
    'verrouiller': 'Bloquear',
    'session_terminee': 'Sessão do gestor encerrada.',
    'qui_es_tu': 'Meu nome',
    'choisir_nom': 'Escolher meu nome',
    'tres_fiable': 'Muito confiável',
    'fiable': 'Confiável',
    'a_surveiller': 'Monitorar',
    'risque': 'Arriscado',
    'tres_risque': 'Muito arriscado',
    'caisse_commune': 'Caixa comum',
    'solde_disponible': 'SALDO DISPONÍVEL',
    'apport': 'Aporte',
    'depense': 'Despesa',
    'penalite': 'Multa',
    'mouvements': 'Movimentos',
    'aucun_mouvement': 'Nenhum movimento registrado.',
    'apport_caisse': 'Aporte ao caixa',
    'depense_caisse': 'Despesa do caixa',
    'appliquer_penalite': 'Aplicar multa',
    'membre_penalise': 'Membro penalizado',
    'description_motif': 'Descrição / Motivo',
    'solde_insuffisant': 'Saldo insuficiente',
    'prets_internes': 'Empréstimos internos',
    'solde_caisse': 'Saldo do caixa',
    'aucun_pret': 'Nenhum empréstimo registrado.',
    'nouveau_pret': 'Novo empréstimo',
    'emprunteur': 'Devedor',
    'taux_interet': 'Taxa de juros (%)',
    'duree_mois': 'Duração (meses)',
    'creer_pret': 'Criar empréstimo',
    'confirmer_pret': 'Confirmar empréstimo',
    'montant_prete': 'Valor emprestado',
    'taux': 'Taxa',
    'duree': 'Duração',
    'total_du': 'Total devido',
    'emprunte': 'Emprestado',
    'rembourse': 'Reembolsado',
    'pret_cree': 'Empréstimo criado com sucesso!',
    'données_invalides': 'Dados inválidos',
    'tirage_certifie': 'Sorteio certificado',
    'tirage_verrouille': 'Sorteio bloqueado',
    'tirage_signe': 'Sorteio bloqueado e assinado!',
    'ordre_passage': 'Ordem de passagem',
    'ordre_actuel': 'Ordem atual',
    'beneficiaire_tour': 'Beneficiário da rodada atual',
    'tour_sur': 'Rodada {n}/{total}',
    'deja_servi': 'Já atendido neste ciclo',
    'seul_gest_tirage': 'Apenas um gestor pode lançar o sorteio.',
    'verrouiller_tirage': 'Bloquear o sorteio',
    'action_definitive': 'Esta ação é definitiva.',
    'notifications': 'Notificações',
    'rappels': 'Lembretes',
    'echeance': 'Vencimento',
    'retard': 'Atrasado',
    'dans_jours': 'em {n} dias',
    'demain': 'Amanhã',
    'aujourdhui': 'Hoje',
    'indicateurs': 'Indicadores',
    'total_cotise': 'Total contribuído',
    'attendu': 'Esperado',
    'membres_a_jour': 'Membros em dia',
    'en_attente': 'Pendente',
    'penalites': 'Multas',
    'prets_en_cours': 'Empréstimos ativos',
    'votes_ouverts': 'Votações abertas',
    'retour_btn': 'Voltar',
    'partager_recapitulatif': 'Compartilhar resumo no WhatsApp',
    'tontine_prete': 'A tontina está pronta. O gestor deve definir a ordem para iniciar a primeira rodada.',
    'tous_servis': 'Todos os membros foram atendidos. Deseja propor um novo ciclo?',
    'recevra': 'Receberá',
    'prochaine_cotisation': 'Próxima contribuição',
    'nom_groupe': 'Nome do grupo',
    'montant_cotisation': 'Valor da contribuição',
    'creer_la_tontine': 'Criar tontina',
    'ouvrir_tontine': 'Abrir tontina',
    'code_rejoindre': 'Código da tontina',
    'entrer_code': 'Inserir código',
    'zone_dangereuse': 'Zona perigosa',
    'supprimer_tontine': 'Excluir tontina',
    'supprimer_confirm': 'Torna a tontina inacessível para todos os membros. O código de convite é invalidado imediatamente. O histórico é preservado.',
    'retour_mes_tontines': 'Voltar às minhas tontinas',
    'tontine_supprimee': 'Tontina excluída',
    'tontine_supprimee_msg': 'Esta tontina foi excluída por seu gestor e não está mais acessível.',
    'tous': 'Todos',
    'score': 'Pontuação',
    'nom': 'Nome',
    'qui_etes_vous': 'Quem é você?',
    'ton_pin': 'Seu PIN',
    'acceder': 'Acessar',
    'inviter_whatsapp': 'Convidar pelo WhatsApp',
    'proposer_retrait': 'Propor retirada',
    'vote_securise_collectif': 'Voto seguro · Decisão coletiva',
    'score_confiance': 'Pontuação de confiança',
    'score_confiance_ia': 'Pontuação de confiança IA',
    'recommandations_ia_consultatif': 'Recomendações de IA (apenas consultivo)',
    'modifier_score_manuel': 'Editar pontuação manualmente',
    'reserve_admin_audit': 'Apenas administradores · Registado em auditoria',
    'nouveau_score': 'Nova pontuação (0-100)',
    'motif_modification': 'Motivo da modificação',
    'motif_modif_hint': 'Razão que justifica esta modificação manual...',
    'motif_proposition': 'Motivo da proposta (obrigatório)',
    'motif_retrait_hint': 'Descreva precisamente as razões que justificam esta proposta de retirada...',
    'quorum_minimum': 'Quórum mínimo',
    'taux_participation_requis': 'Taxa de participação requerida',
    'majorite_requise': 'Maioria requerida',
    'votes_pour_requis': 'Votos Sim necessários para adoção',
    'votre_pin_gest': 'O seu PIN de gestor',
    'creer_vote_retrait': 'Criar voto de retirada',
    'conditions_vote_retrait': 'Condições do voto de retirada',
    'recalculer': 'Recalcular',
    'tab_score_ia': 'Pontuação & IA',
    'decisions': 'Decisões',
    'espace_admin': 'Painel de administração',
    'cle_admin': 'Chave de administrador',
    'acceder_btn': 'Acessar',
    'cle_incorrecte': 'Chave incorreta ou erro de rede.',
    'demandes': 'Solicitações',
    'tontines_admin': 'Tontinas',
    'aucune_demande': 'Sem solicitações.',
    'refuser_demande': 'Recusar solicitação',
    'motif_refus': 'Motivo da recusa',
    'confirmer_refus': 'Confirmar recusa',
    'premium_active': 'Premium ativado!',
    'premium_desactive': 'Premium desativado.',
    'activer_premium': 'Ativar Premium',
    'outils_dev': 'Ferramentas de desenvolvimento',
    'acces_reserve': 'Acesso reservado — não compartilhar',
    'tester_connexion': 'Testar conexão Supabase',
    'reconfigurer': 'Reconfigurar credenciais',
    'retirer_liste': 'Remover da minha lista',
    'retirer_tontine_titre': 'Remover da lista?',
    'retirer_tontine_msg': 'Deseja remover esta tontina da sua lista local?\nA tontina permanece acessível com seu código.',
    'code_label': 'Código: ',
    'espace_administrateur': 'Painel de administração',
    'slogan_accueil': 'Cada contribuição está online. Todos veem o mesmo, ao vivo.',
    'titre_accueil': 'Minhas tontinas',
    'tontine_sans_dispute': 'A tontina sem disputas',
    'tontine_description': 'Crie uma tontina e compartilhe seu código, ou entre na do seu grupo para acompanhar tudo ao vivo.',
    'diagnostic_connexion': 'Diagnóstico de conexão',
    'retester': 'Testar novamente',
    'test_en_cours': 'Teste em andamento…',
    'devises_associees': 'Moedas associadas',
    'chargement_cotisations': 'Carregando contribuições…',
    'relancer_retardataires': 'Lembrar todos os atrasados',
    'ignorer': 'Ignorar',
    'envoyer_pin_whatsapp': 'Enviar PIN pelo WhatsApp',
    'communication_pin': 'Comunique este PIN ao membro para que ele o altere.',
    'pin_provisoire': 'PIN provisório',
    'reinitialiser_pin': 'Redefinir PIN',
    'generer_pin': 'Gerar e atribuir PIN',
    'mois': 'meses',
    'cycles': 'ciclos',
    'chargement_dashboard': 'Carregando painel…',
    'donnees_temps_reel': 'Dados em tempo real do Supabase',
    'aucune_donnee': 'Sem dados disponíveis',
    'aucune_alerte': 'Sem alertas ativos',
    'actif': 'Ativos',
    'expire': 'Expirados',
    'en_attente_statut': 'Pendente',
    'mensuel': 'Mensal',
    'annuel': 'Anual',
    'suivi_abonnements': 'Acompanhamento de assinaturas',
    'montant_total_actif': 'Valor total ativo',
    'estime_ce_mois': 'Estimado este mês',
    'retirer': 'Remover',
    'mode_paiement_label': 'Método de pagamento',
    'mois_label': '{n} meses',
    'tour_n': 'N.º {n}',
    'echéance_depassee': 'Vencido ({n} d)',
    'jours_restants': 'Dias restantes',
    'membres_modules': 'Módulos',
    'reponse_copiee': 'Resposta copiada',
    'whatsapp_indisponible': 'WhatsApp não disponível.',
    'erreur_export_pdf': 'Erro ao exportar PDF: ',
    'erreur_whatsapp': 'Não foi possível abrir o WhatsApp.',
    'donnees_incompletes': 'Dados incompletos',
    'identifiant_vote_manquant': 'Erro: identificador de votação ausente. Recarregue a tontina.',
    'deja_vote': 'Você já votou.',
    'pin_gestionnaire_incorrect': 'PIN do gestor incorreto. Tente novamente.',
    'confirmer_vote': 'Confirmar seu voto',
    'pin_membre': 'Seu PIN de membro',
    'pin_de': 'PIN de ',
    'ton_vote': 'Seu voto',
    'ton_pin_vote': 'Seu PIN de voto',
    'oui_non_abstention': 'Sim / Não / Abstenção',
    'erreur_inconnue': 'Erro desconhecido.',
    'rechargez_page': 'Nenhum membro disponível. Recarregue a página.',
    'erreur_pdf': 'Erro PDF: ',
  },

  // ════════════════════════════════════════════════════════════════════════
  // 🇸🇦 عربي
  // ════════════════════════════════════════════════════════════════════════
  'ar': {
    'app_nom': 'TontineClair',
    'app_slogan': 'تونتيناتك بكل شفافية',
    'accueil': 'الرئيسية',
    'mes_tontines': 'تونتيناتي',
    'creer_tontine': 'إنشاء تونتين',
    'rejoindre': 'الانضمام',
    'rejoindre_tontine': 'الانضمام إلى تونتين',
    'tableau_de_bord': 'لوحة القيادة',
    'cotisations': 'الاشتراكات',
    'caisse': 'الصندوق',
    'prets': 'القروض',
    'tirage': 'القرعة',
    'votes': 'التصويتات',
    'membres': 'الأعضاء',
    'journal': 'السجل',
    'historique': 'التاريخ',
    'classement': 'التصنيف',
    'abonnement': 'الاشتراك',
    'parametres': 'الإعدادات',
    'retour': 'رجوع',
    'fermer': 'إغلاق',
    'annuler': 'إلغاء',
    'confirmer': 'تأكيد',
    'enregistrer': 'حفظ',
    'supprimer': 'حذف',
    'modifier': 'تعديل',
    'details': 'التفاصيل',
    'partager': 'مشاركة',
    'appliquer': 'تطبيق',
    'reessayer': 'إعادة المحاولة',
    'rechercher': 'بحث',
    'nouveau': 'جديد',
    'oui': 'نعم',
    'non': 'لا',
    'langue': 'اللغة',
    'choisir_langue': 'اختر اللغة',
    'langue_actuelle': 'اللغة الحالية',
    'langue_choisie': 'اللغة المختارة',
    'langue_modifiee': 'تم تغيير اللغة بنجاح',
    'langues_disponibles': 'اللغات المتاحة',
    'erreur': 'خطأ',
    'succes': 'نجاح',
    'chargement': 'جارٍ التحميل…',
    'bienvenue': 'مرحباً',
    'deconnexion': 'تسجيل الخروج',
    'connexion_requise': 'يلزم الاتصال',
    'verifier_connexion': 'تحقق من اتصالك بالإنترنت',
    'tontine_introuvable': 'لم يتم العثور على التونتين',
    'aucune_tontine': 'لا توجد تونتينات',
    'code_tontine': 'رمز التونتين',
    'nom_tontine': 'اسم التونتين',
    'montant': 'المبلغ',
    'devise': 'العملة',
    'periodicite': 'التكرار',
    'membres_count': 'أعضاء',
    'tour': 'الدور',
    'cycle': 'الدورة',
    'beneficiaire': 'المستفيد',
    'total': 'المجموع',
    'solde': 'الرصيد',
    'caisse_solde': 'رصيد الصندوق',
    'paye': 'مدفوع',
    'non_paye': 'غير مدفوع',
    'paiement': 'الدفع',
    'confirmer_paiement': 'تأكيد الدفع',
    'annuler_paiement': 'إلغاء الدفع',
    'paiement_enregistre': 'تم تسجيل الدفع!',
    'paiement_annule': 'تم إلغاء الدفع وتحديث السجل.',
    'methode_paiement': 'طريقة الدفع',
    'exporter_pdf': 'تصدير PDF',
    'vote_ouvert': 'تصويت مفتوح',
    'vote_clos': 'تصويت مغلق',
    'abstention': 'امتناع',
    'ont_vote': 'صوّتوا',
    'voter': 'تصويت',
    'vote_libre': 'تصويت حر',
    'vote_binaire': 'نعم / لا',
    'vote_enregistre': 'تم تسجيل التصويت!',
    'vote_cree': 'تم فتح التصويت!',
    'ouvrir_vote': 'فتح التصويت',
    'cloture_vote': 'إغلاق التصويت',
    'nouveau_vote': 'تصويت جديد',
    'chargement_votes': 'جارٍ تحميل التصويتات…',
    'aucun_vote': 'لا يوجد تصويت نشط.',
    'question_vote': 'السؤال / موضوع التصويت',
    'type_vote': 'نوع التصويت',
    'question_requise': 'السؤال مطلوب',
    'creer_vote': 'إنشاء تصويت',
    'restant': 'متبقٍ',
    'verrouille': 'مقفل',
    'nouveau_cycle': 'دورة جديدة',
    'cycle_termine': 'اكتملت الدورة',
    'demarrer_cycle': 'بدء الدورة',
    'proposer_nouveau_cycle': 'اقتراح دورة جديدة',
    'vote_redemarrage': 'مشاهدة تصويت إعادة التشغيل',
    'pin': 'الرمز السري',
    'entrer_pin': 'أدخل رمزك السري',
    'pin_incorrect': 'رمز سري غير صحيح',
    'changer_pin': 'تغيير رمزي السري',
    'nouveau_pin': 'رمز سري جديد',
    'ancien_pin': 'الرمز السري القديم (مؤقت)',
    'pin_gestionnaire': 'رمز سري المدير',
    'confirmer_pin': 'تأكيد برمزك السري',
    'pin_trop_court': 'الرمز السري قصير جداً.',
    'pin_attribue': 'تم تعيين الرمز السري',
    'gestionnaire': 'المدير',
    'membre': 'عضو',
    'ajouter_membre': 'إضافة عضو',
    'nouveau_membre': 'اسم العضو الجديد',
    'aucun_membre': 'لا يوجد أعضاء للعرض.',
    'mode_gestion': 'وضع الإدارة · ',
    'mode_consultation': 'وضع المشاهدة',
    'acces_gestionnaire': 'دخول المدير',
    'verrouiller': 'قفل',
    'session_terminee': 'انتهت جلسة المدير.',
    'qui_es_tu': 'اسمي',
    'choisir_nom': 'اختر اسمي',
    'tres_fiable': 'موثوق جداً',
    'fiable': 'موثوق',
    'a_surveiller': 'تحت المراقبة',
    'risque': 'محفوف بالمخاطر',
    'tres_risque': 'خطير جداً',
    'caisse_commune': 'الصندوق المشترك',
    'solde_disponible': 'الرصيد المتاح',
    'apport': 'إيداع',
    'depense': 'مصروف',
    'penalite': 'غرامة',
    'mouvements': 'الحركات',
    'aucun_mouvement': 'لا توجد حركات مسجلة.',
    'apport_caisse': 'إيداع في الصندوق',
    'depense_caisse': 'مصروف من الصندوق',
    'appliquer_penalite': 'تطبيق غرامة',
    'membre_penalise': 'العضو المغرَّم',
    'description_motif': 'الوصف / السبب',
    'solde_insuffisant': 'رصيد غير كافٍ',
    'prets_internes': 'القروض الداخلية',
    'solde_caisse': 'رصيد الصندوق',
    'aucun_pret': 'لا توجد قروض مسجلة.',
    'nouveau_pret': 'قرض جديد',
    'emprunteur': 'المقترض',
    'taux_interet': 'معدل الفائدة (%)',
    'duree_mois': 'المدة (أشهر)',
    'creer_pret': 'إنشاء قرض',
    'confirmer_pret': 'تأكيد القرض',
    'montant_prete': 'المبلغ المُقرَض',
    'taux': 'المعدل',
    'duree': 'المدة',
    'total_du': 'المجموع المستحق',
    'emprunte': 'مُقترَض',
    'rembourse': 'مُسدَّد',
    'pret_cree': 'تم إنشاء القرض بنجاح!',
    'données_invalides': 'بيانات غير صالحة',
    'tirage_certifie': 'قرعة معتمدة',
    'tirage_verrouille': 'القرعة مقفلة',
    'tirage_signe': 'تم قفل القرعة وتوقيعها!',
    'ordre_passage': 'ترتيب المرور',
    'ordre_actuel': 'الترتيب الحالي',
    'beneficiaire_tour': 'مستفيد الدور الحالي',
    'tour_sur': 'الدور {n}/{total}',
    'deja_servi': 'تمت خدمته في هذه الدورة',
    'seul_gest_tirage': 'فقط المدير يمكنه إجراء القرعة.',
    'verrouiller_tirage': 'قفل القرعة',
    'action_definitive': 'هذا الإجراء نهائي.',
    'notifications': 'الإشعارات',
    'rappels': 'التذكيرات',
    'echeance': 'تاريخ الاستحقاق',
    'retard': 'متأخر',
    'dans_jours': 'خلال {n} أيام',
    'demain': 'غداً',
    'aujourdhui': 'اليوم',
    'indicateurs': 'المؤشرات',
    'total_cotise': 'إجمالي المُحصَّل',
    'attendu': 'المتوقع',
    'membres_a_jour': 'الأعضاء المُحدَّثون',
    'en_attente': 'في الانتظار',
    'penalites': 'الغرامات',
    'prets_en_cours': 'القروض النشطة',
    'votes_ouverts': 'التصويتات المفتوحة',
    'retour_btn': 'رجوع',
    'partager_recapitulatif': 'مشاركة الملخص على واتساب',
    'tontine_prete': 'التونتين جاهز. يجب على المدير تحديد الترتيب لبدء الجولة الأولى.',
    'tous_servis': 'تمت خدمة جميع الأعضاء. هل تريد اقتراح دورة جديدة؟',
    'recevra': 'سيستلم',
    'prochaine_cotisation': 'الاشتراك القادم',
    'nom_groupe': 'اسم المجموعة',
    'montant_cotisation': 'مبلغ الاشتراك',
    'creer_la_tontine': 'إنشاء التونتين',
    'ouvrir_tontine': 'فتح التونتين',
    'code_rejoindre': 'رمز التونتين',
    'entrer_code': 'أدخل الرمز',
    'zone_dangereuse': 'منطقة خطرة',
    'supprimer_tontine': 'حذف التونتين',
    'supprimer_confirm': 'يجعل التونتين غير قابل للوصول لجميع الأعضاء. يتم إبطال رمز الدعوة فوراً. يتم الاحتفاظ بالسجل.',
    'retour_mes_tontines': 'العودة إلى تونتيناتي',
    'tontine_supprimee': 'تم حذف التونتين',
    'tontine_supprimee_msg': 'تم حذف هذا التونتين من قِبل مديره ولم يعد متاحاً.',
    'tous': 'الكل',
    'score': 'النقاط',
    'nom': 'الاسم',
    'qui_etes_vous': 'من أنت؟',
    'ton_pin': 'رمزك السري',
    'acceder': 'دخول',
    'inviter_whatsapp': 'دعوة عبر واتساب',
    'proposer_retrait': 'اقتراح الانسحاب',
    'vote_securise_collectif': 'تصويت آمن · قرار جماعي',
    'score_confiance': 'نتيجة الثقة',
    'score_confiance_ia': 'نتيجة الثقة بالذكاء الاصطناعي',
    'recommandations_ia_consultatif': 'توصيات الذكاء الاصطناعي (استشارية فقط)',
    'modifier_score_manuel': 'تعديل النتيجة يدوياً',
    'reserve_admin_audit': 'للمسؤولين فقط · مسجل في سجل التدقيق',
    'nouveau_score': 'النتيجة الجديدة (0-100)',
    'motif_modification': 'سبب التعديل',
    'motif_modif_hint': 'السبب المبرر لهذا التعديل اليدوي...',
    'motif_proposition': 'سبب الاقتراح (إلزامي)',
    'motif_retrait_hint': 'صف بدقة الأسباب المبررة لهذا اقتراح الانسحاب...',
    'quorum_minimum': 'الحد الأدنى للنصاب',
    'taux_participation_requis': 'نسبة المشاركة المطلوبة',
    'majorite_requise': 'الأغلبية المطلوبة',
    'votes_pour_requis': 'أصوات نعم المطلوبة للاعتماد',
    'votre_pin_gest': 'رمز PIN المدير الخاص بك',
    'creer_vote_retrait': 'إنشاء تصويت الانسحاب',
    'conditions_vote_retrait': 'شروط تصويت الانسحاب',
    'recalculer': 'إعادة الحساب',
    'tab_score_ia': 'النتيجة والذكاء الاصطناعي',
    'decisions': 'القرارات',
    'espace_admin': 'لوحة الإدارة',
    'cle_admin': 'مفتاح المدير',
    'acceder_btn': 'دخول',
    'cle_incorrecte': 'مفتاح غير صحيح أو خطأ في الشبكة.',
    'demandes': 'الطلبات',
    'tontines_admin': 'التونتينات',
    'aucune_demande': 'لا توجد طلبات.',
    'refuser_demande': 'رفض الطلب',
    'motif_refus': 'سبب الرفض',
    'confirmer_refus': 'تأكيد الرفض',
    'premium_active': 'تم تفعيل البريميوم!',
    'premium_desactive': 'تم إلغاء تفعيل البريميوم.',
    'activer_premium': 'تفعيل البريميوم',
    'outils_dev': 'أدوات المطور',
    'acces_reserve': 'وصول محجوز — لا تشارك',
    'tester_connexion': 'اختبار اتصال Supabase',
    'reconfigurer': 'إعادة تكوين بيانات الاعتماد',
    'retirer_liste': 'إزالة من قائمتي',
    'retirer_tontine_titre': 'إزالة من القائمة؟',
    'retirer_tontine_msg': 'هل تريد إزالة هذا التونتين من قائمتك المحلية؟\nيبقى التونتين متاحاً برمزه.',
    'code_label': 'الرمز: ',
    'espace_administrateur': 'لوحة الإدارة',
    'slogan_accueil': 'كل اشتراك على الإنترنت. الجميع يرى نفس الشيء، مباشرة.',
    'titre_accueil': 'تونتيناتي',
    'tontine_sans_dispute': 'التونتين بدون نزاعات',
    'tontine_description': 'أنشئ تونتيناً وشارك رمزه، أو انضم إلى تونتين مجموعتك لمتابعة كل شيء مباشرة.',
    'diagnostic_connexion': 'تشخيص الاتصال',
    'retester': 'إعادة الاختبار',
    'test_en_cours': 'الاختبار جارٍ…',
    'devises_associees': 'العملات المرتبطة',
    'chargement_cotisations': 'جارٍ تحميل الاشتراكات…',
    'relancer_retardataires': 'تذكير جميع المتأخرين',
    'ignorer': 'تجاهل',
    'envoyer_pin_whatsapp': 'إرسال الرمز السري عبر واتساب',
    'communication_pin': 'أبلغ هذا الرمز السري للعضو ليتمكن من تغييره.',
    'pin_provisoire': 'رمز سري مؤقت',
    'reinitialiser_pin': 'إعادة تعيين الرمز السري',
    'generer_pin': 'إنشاء وتعيين الرمز السري',
    'mois': 'أشهر',
    'cycles': 'دورات',
    'chargement_dashboard': 'جارٍ تحميل اللوحة…',
    'donnees_temps_reel': 'بيانات في الوقت الفعلي من Supabase',
    'aucune_donnee': 'لا توجد بيانات متاحة',
    'aucune_alerte': 'لا توجد تنبيهات نشطة',
    'actif': 'النشطة',
    'expire': 'المنتهية',
    'en_attente_statut': 'في الانتظار',
    'mensuel': 'شهري',
    'annuel': 'سنوي',
    'suivi_abonnements': 'متابعة الاشتراكات',
    'montant_total_actif': 'إجمالي المبلغ النشط',
    'estime_ce_mois': 'المُقدَّر هذا الشهر',
    'retirer': 'إزالة',
    'mode_paiement_label': 'طريقة الدفع',
    'mois_label': '{n} أشهر',
    'tour_n': 'رقم {n}',
    'echéance_depassee': 'تجاوز الموعد ({n} ي)',
    'jours_restants': 'الأيام المتبقية',
    'membres_modules': 'الوحدات',
    'reponse_copiee': 'تم نسخ الرد',
    'whatsapp_indisponible': 'واتساب غير متاح.',
    'erreur_export_pdf': 'خطأ في تصدير PDF: ',
    'erreur_whatsapp': 'تعذر فتح واتساب.',
    'donnees_incompletes': 'بيانات غير مكتملة',
    'identifiant_vote_manquant': 'خطأ: معرّف التصويت مفقود. أعد تحميل التونتين.',
    'deja_vote': 'لقد صوّت بالفعل.',
    'pin_gestionnaire_incorrect': 'رمز سري المدير غير صحيح. حاول مرة أخرى.',
    'confirmer_vote': 'تأكيد تصويتك',
    'pin_membre': 'رمزك السري كعضو',
    'pin_de': 'رمز سري ',
    'ton_vote': 'تصويتك',
    'ton_pin_vote': 'رمزك السري للتصويت',
    'oui_non_abstention': 'نعم / لا / امتناع',
    'erreur_inconnue': 'خطأ غير معروف.',
    'rechargez_page': 'لا يوجد أعضاء متاحون. أعد تحميل الصفحة.',
    'erreur_pdf': 'خطأ PDF: ',
  },

};