// ─────────────────────────────────────────────────────────────────────────────
// AppLocalizations — Traductions de l'interface TontineClair
//
// Langues : FR · EN · AR · PT · ES · SW · HA · AM
// Usage   : context.tr('cle')  ou  AppLocalizations.of(context).get('cle')
// ─────────────────────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import '../services/locale_service.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Extension de commodité sur BuildContext
// ─────────────────────────────────────────────────────────────────────────────

extension AppLocalizationsExt on BuildContext {
  /// Traduit une clé dans la langue active. Retourne la clé si non trouvée.
  String tr(String key) => AppLocalizations.of(this).get(key);
}

// ─────────────────────────────────────────────────────────────────────────────
// Classe principale
// ─────────────────────────────────────────────────────────────────────────────

class AppLocalizations {
  final String langueCode;

  const AppLocalizations(this.langueCode);

  /// Récupère le LocaleService depuis le context et retourne l'instance.
  static AppLocalizations of(BuildContext context) {
    final service = context.findAncestorStateOfType<_AppLocalizationsWrapperState>();
    return AppLocalizations(service?.langueCode ?? 'fr');
  }

  /// Traduit une clé. Fallback : français, puis la clé elle-même.
  String get(String key) {
    final langMap = _translations[langueCode];
    if (langMap != null && langMap.containsKey(key)) return langMap[key]!;
    // Fallback français
    final frMap = _translations['fr'];
    if (frMap != null && frMap.containsKey(key)) return frMap[key]!;
    return key;
  }

  // ── Raccourcis directs (optionnel, pour IDE autocomplete) ────────────────
  String get appNom              => get('app_nom');
  String get accueil             => get('accueil');
  String get mesTontines         => get('mes_tontines');
  String get creerTontine        => get('creer_tontine');
  String get rejoindre           => get('rejoindre');
  String get tableauDeBord       => get('tableau_de_bord');
  String get cotisations         => get('cotisations');
  String get caisse              => get('caisse');
  String get prets               => get('prets');
  String get tirage              => get('tirage');
  String get votes               => get('votes');
  String get membres             => get('membres');
  String get journal             => get('journal');
  String get parametres          => get('parametres');
  String get langue              => get('langue');
  String get choisirLangue       => get('choisir_langue');
  String get enregistrer         => get('enregistrer');
  String get annuler             => get('annuler');
  String get confirmer           => get('confirmer');
  String get retour              => get('retour');
  String get erreur              => get('erreur');
  String get succes              => get('succes');
  String get chargement          => get('chargement');
  String get deconnexion         => get('deconnexion');
}

// ─────────────────────────────────────────────────────────────────────────────
// Widget wrapper InheritedWidget pour propager la langue dans l'arbre
// ─────────────────────────────────────────────────────────────────────────────

class AppLocalizationsWrapper extends StatefulWidget {
  final Widget child;
  final LocaleService localeService;

  const AppLocalizationsWrapper({
    super.key,
    required this.child,
    required this.localeService,
  });

  @override
  State<AppLocalizationsWrapper> createState() => _AppLocalizationsWrapperState();
}

class _AppLocalizationsWrapperState extends State<AppLocalizationsWrapper> {
  String get langueCode => widget.localeService.langue.code;

  @override
  void initState() {
    super.initState();
    widget.localeService.addListener(_onLangueChange);
  }

  @override
  void dispose() {
    widget.localeService.removeListener(_onLangueChange);
    super.dispose();
  }

  void _onLangueChange() => setState(() {});

  @override
  Widget build(BuildContext context) => widget.child;
}

// ─────────────────────────────────────────────────────────────────────────────
// Dictionnaire des traductions
// ─────────────────────────────────────────────────────────────────────────────

const Map<String, Map<String, String>> _translations = {

  // ════════════════════════════════════════════════════════════════════════════
  // 🇫🇷 FRANÇAIS
  // ════════════════════════════════════════════════════════════════════════════
  'fr': {
    'app_nom':              'TontineClair',
    'app_slogan':           'Vos tontines, en toute transparence',
    'accueil':              'Accueil',
    'mes_tontines':         'Mes tontines',
    'creer_tontine':        'Créer une tontine',
    'rejoindre':            'Rejoindre',
    'rejoindre_tontine':    'Rejoindre une tontine',
    'tableau_de_bord':      'Tableau de bord',
    'cotisations':          'Cotisations',
    'caisse':               'Caisse',
    'prets':                'Prêts',
    'tirage':               'Tirage au sort',
    'votes':                'Votes',
    'membres':              'Membres',
    'journal':              'Journal',
    'historique':           'Historique',
    'classement':           'Classement',
    'abonnement':           'Abonnement',
    'parametres':           'Paramètres',
    'langue':               'Langue',
    'choisir_langue':       'Choisir la langue',
    'langue_actuelle':      'Langue actuelle',
    'langue_choisie':       'Langue sélectionnée',
    'langue_modifiee':      'Langue modifiée avec succès',
    'enregistrer':          'Enregistrer',
    'annuler':              'Annuler',
    'confirmer':            'Confirmer',
    'retour':               'Retour',
    'fermer':               'Fermer',
    'erreur':               'Erreur',
    'succes':               'Succès',
    'chargement':           'Chargement…',
    'aucune_tontine':       'Aucune tontine',
    'code_tontine':         'Code de la tontine',
    'nom_tontine':          'Nom de la tontine',
    'montant':              'Montant',
    'devise':               'Devise',
    'periodicite':          'Périodicité',
    'membres_count':        'membres',
    'tour':                 'Tour',
    'cycle':                'Cycle',
    'beneficiaire':         'Bénéficiaire',
    'paye':                 'Payé',
    'non_paye':             'Non payé',
    'total':                'Total',
    'solde':                'Solde',
    'caisse_solde':         'Solde de caisse',
    'vote_ouvert':          'Vote ouvert',
    'vote_clos':            'Vote clôturé',
    'oui':                  'Oui',
    'non':                  'Non',
    'abstention':           'Abstention',
    'ont_vote':             'ont voté',
    'restant':              'restant',
    'verrouille':           'Verrouillé',
    'nouveau_cycle':        'Nouveau cycle',
    'cycle_termine':        'Cycle terminé',
    'deconnexion':          'Déconnexion',
    'pin':                  'PIN',
    'entrer_pin':           'Entrer votre PIN',
    'pin_incorrect':        'PIN incorrect',
    'gestionnaire':         'Gestionnaire',
    'membre':               'Membre',
    'ajouter_membre':       'Ajouter un membre',
    'supprimer':            'Supprimer',
    'modifier':             'Modifier',
    'details':              'Détails',
    'partager':             'Partager',
    'exporter_pdf':         'Exporter PDF',
    'notifications':        'Notifications',
    'rappels':              'Rappels',
    'echeance':             'Échéance',
    'retard':               'En retard',
    'dans_jours':           'dans {n} jours',
    'demain':               'Demain',
    'aujourdhui':           "Aujourd'hui",
    'bienvenue':            'Bienvenue',
    'nouveau':              'Nouveau',
    'rechercher':           'Rechercher',
    'tontine_introuvable':  'Tontine introuvable',
    'connexion_requise':    'Connexion requise',
    'verifier_connexion':   'Vérifiez votre connexion internet',
    'reessayer':            'Réessayer',
    'langues_disponibles':  'Langues disponibles',
    'devises_associees':    'Devises associées',
    'appliquer':            'Appliquer',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 🇬🇧 ENGLISH
  // ════════════════════════════════════════════════════════════════════════════
  'en': {
    'app_nom':              'TontineClair',
    'app_slogan':           'Your tontines, with full transparency',
    'accueil':              'Home',
    'mes_tontines':         'My tontines',
    'creer_tontine':        'Create a tontine',
    'rejoindre':            'Join',
    'rejoindre_tontine':    'Join a tontine',
    'tableau_de_bord':      'Dashboard',
    'cotisations':          'Contributions',
    'caisse':               'Treasury',
    'prets':                'Loans',
    'tirage':               'Draw',
    'votes':                'Votes',
    'membres':              'Members',
    'journal':              'Journal',
    'historique':           'History',
    'classement':           'Rankings',
    'abonnement':           'Subscription',
    'parametres':           'Settings',
    'langue':               'Language',
    'choisir_langue':       'Choose language',
    'langue_actuelle':      'Current language',
    'langue_choisie':       'Selected language',
    'langue_modifiee':      'Language changed successfully',
    'enregistrer':          'Save',
    'annuler':              'Cancel',
    'confirmer':            'Confirm',
    'retour':               'Back',
    'fermer':               'Close',
    'erreur':               'Error',
    'succes':               'Success',
    'chargement':           'Loading…',
    'aucune_tontine':       'No tontines',
    'code_tontine':         'Tontine code',
    'nom_tontine':          'Tontine name',
    'montant':              'Amount',
    'devise':               'Currency',
    'periodicite':          'Frequency',
    'membres_count':        'members',
    'tour':                 'Round',
    'cycle':                'Cycle',
    'beneficiaire':         'Beneficiary',
    'paye':                 'Paid',
    'non_paye':             'Unpaid',
    'total':                'Total',
    'solde':                'Balance',
    'caisse_solde':         'Treasury balance',
    'vote_ouvert':          'Open vote',
    'vote_clos':            'Closed vote',
    'oui':                  'Yes',
    'non':                  'No',
    'abstention':           'Abstain',
    'ont_vote':             'have voted',
    'restant':              'remaining',
    'verrouille':           'Locked',
    'nouveau_cycle':        'New cycle',
    'cycle_termine':        'Cycle complete',
    'deconnexion':          'Log out',
    'pin':                  'PIN',
    'entrer_pin':           'Enter your PIN',
    'pin_incorrect':        'Incorrect PIN',
    'gestionnaire':         'Manager',
    'membre':               'Member',
    'ajouter_membre':       'Add member',
    'supprimer':            'Delete',
    'modifier':             'Edit',
    'details':              'Details',
    'partager':             'Share',
    'exporter_pdf':         'Export PDF',
    'notifications':        'Notifications',
    'rappels':              'Reminders',
    'echeance':             'Due date',
    'retard':               'Overdue',
    'dans_jours':           'in {n} days',
    'demain':               'Tomorrow',
    'aujourdhui':           'Today',
    'bienvenue':            'Welcome',
    'nouveau':              'New',
    'rechercher':           'Search',
    'tontine_introuvable':  'Tontine not found',
    'connexion_requise':    'Connection required',
    'verifier_connexion':   'Check your internet connection',
    'reessayer':            'Retry',
    'langues_disponibles':  'Available languages',
    'devises_associees':    'Associated currencies',
    'appliquer':            'Apply',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 🇸🇦 ARABE
  // ════════════════════════════════════════════════════════════════════════════
  'ar': {
    'app_nom':              'TontineClair',
    'app_slogan':           'تونتيناتك بكل شفافية',
    'accueil':              'الرئيسية',
    'mes_tontines':         'تونتيناتي',
    'creer_tontine':        'إنشاء تونتين',
    'rejoindre':            'الانضمام',
    'rejoindre_tontine':    'الانضمام إلى تونتين',
    'tableau_de_bord':      'لوحة القيادة',
    'cotisations':          'الاشتراكات',
    'caisse':               'الصندوق',
    'prets':                'القروض',
    'tirage':               'القرعة',
    'votes':                'التصويتات',
    'membres':              'الأعضاء',
    'journal':              'السجل',
    'historique':           'التاريخ',
    'classement':           'التصنيف',
    'abonnement':           'الاشتراك',
    'parametres':           'الإعدادات',
    'langue':               'اللغة',
    'choisir_langue':       'اختر اللغة',
    'langue_actuelle':      'اللغة الحالية',
    'langue_choisie':       'اللغة المختارة',
    'langue_modifiee':      'تم تغيير اللغة بنجاح',
    'enregistrer':          'حفظ',
    'annuler':              'إلغاء',
    'confirmer':            'تأكيد',
    'retour':               'رجوع',
    'fermer':               'إغلاق',
    'erreur':               'خطأ',
    'succes':               'نجاح',
    'chargement':           'جارٍ التحميل…',
    'aucune_tontine':       'لا توجد تونتينات',
    'code_tontine':         'رمز التونتين',
    'nom_tontine':          'اسم التونتين',
    'montant':              'المبلغ',
    'devise':               'العملة',
    'periodicite':          'التكرار',
    'membres_count':        'أعضاء',
    'tour':                 'الدور',
    'cycle':                'الدورة',
    'beneficiaire':         'المستفيد',
    'paye':                 'مدفوع',
    'non_paye':             'غير مدفوع',
    'total':                'المجموع',
    'solde':                'الرصيد',
    'caisse_solde':         'رصيد الصندوق',
    'vote_ouvert':          'تصويت مفتوح',
    'vote_clos':            'تصويت مغلق',
    'oui':                  'نعم',
    'non':                  'لا',
    'abstention':           'امتناع',
    'ont_vote':             'صوّتوا',
    'restant':              'متبقٍ',
    'verrouille':           'مقفل',
    'nouveau_cycle':        'دورة جديدة',
    'cycle_termine':        'اكتملت الدورة',
    'deconnexion':          'تسجيل الخروج',
    'pin':                  'الرمز السري',
    'entrer_pin':           'أدخل رمزك السري',
    'pin_incorrect':        'رمز سري غير صحيح',
    'gestionnaire':         'المدير',
    'membre':               'عضو',
    'ajouter_membre':       'إضافة عضو',
    'supprimer':            'حذف',
    'modifier':             'تعديل',
    'details':              'التفاصيل',
    'partager':             'مشاركة',
    'exporter_pdf':         'تصدير PDF',
    'notifications':        'الإشعارات',
    'rappels':              'التذكيرات',
    'echeance':             'تاريخ الاستحقاق',
    'retard':               'متأخر',
    'dans_jours':           'خلال {n} أيام',
    'demain':               'غداً',
    'aujourdhui':           'اليوم',
    'bienvenue':            'مرحباً',
    'nouveau':              'جديد',
    'rechercher':           'بحث',
    'tontine_introuvable':  'لم يتم العثور على التونتين',
    'connexion_requise':    'يلزم الاتصال',
    'verifier_connexion':   'تحقق من اتصالك بالإنترنت',
    'reessayer':            'إعادة المحاولة',
    'langues_disponibles':  'اللغات المتاحة',
    'devises_associees':    'العملات المرتبطة',
    'appliquer':            'تطبيق',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 🇧🇷 PORTUGAIS
  // ════════════════════════════════════════════════════════════════════════════
  'pt': {
    'app_nom':              'TontineClair',
    'app_slogan':           'Suas tontinas com total transparência',
    'accueil':              'Início',
    'mes_tontines':         'Minhas tontinas',
    'creer_tontine':        'Criar tontina',
    'rejoindre':            'Entrar',
    'rejoindre_tontine':    'Entrar em uma tontina',
    'tableau_de_bord':      'Painel',
    'cotisations':          'Contribuições',
    'caisse':               'Caixa',
    'prets':                'Empréstimos',
    'tirage':               'Sorteio',
    'votes':                'Votos',
    'membres':              'Membros',
    'journal':              'Diário',
    'historique':           'Histórico',
    'classement':           'Classificação',
    'abonnement':           'Assinatura',
    'parametres':           'Configurações',
    'langue':               'Idioma',
    'choisir_langue':       'Escolher idioma',
    'langue_actuelle':      'Idioma atual',
    'langue_choisie':       'Idioma selecionado',
    'langue_modifiee':      'Idioma alterado com sucesso',
    'enregistrer':          'Salvar',
    'annuler':              'Cancelar',
    'confirmer':            'Confirmar',
    'retour':               'Voltar',
    'fermer':               'Fechar',
    'erreur':               'Erro',
    'succes':               'Sucesso',
    'chargement':           'Carregando…',
    'aucune_tontine':       'Nenhuma tontina',
    'code_tontine':         'Código da tontina',
    'nom_tontine':          'Nome da tontina',
    'montant':              'Valor',
    'devise':               'Moeda',
    'periodicite':          'Periodicidade',
    'membres_count':        'membros',
    'tour':                 'Rodada',
    'cycle':                'Ciclo',
    'beneficiaire':         'Beneficiário',
    'paye':                 'Pago',
    'non_paye':             'Não pago',
    'total':                'Total',
    'solde':                'Saldo',
    'caisse_solde':         'Saldo do caixa',
    'vote_ouvert':          'Votação aberta',
    'vote_clos':            'Votação encerrada',
    'oui':                  'Sim',
    'non':                  'Não',
    'abstention':           'Abstenção',
    'ont_vote':             'votaram',
    'restant':              'restante',
    'verrouille':           'Bloqueado',
    'nouveau_cycle':        'Novo ciclo',
    'cycle_termine':        'Ciclo concluído',
    'deconnexion':          'Sair',
    'pin':                  'PIN',
    'entrer_pin':           'Insira seu PIN',
    'pin_incorrect':        'PIN incorreto',
    'gestionnaire':         'Gestor',
    'membre':               'Membro',
    'ajouter_membre':       'Adicionar membro',
    'supprimer':            'Excluir',
    'modifier':             'Editar',
    'details':              'Detalhes',
    'partager':             'Compartilhar',
    'exporter_pdf':         'Exportar PDF',
    'notifications':        'Notificações',
    'rappels':              'Lembretes',
    'echeance':             'Vencimento',
    'retard':               'Atrasado',
    'dans_jours':           'em {n} dias',
    'demain':               'Amanhã',
    'aujourdhui':           'Hoje',
    'bienvenue':            'Bem-vindo',
    'nouveau':              'Novo',
    'rechercher':           'Pesquisar',
    'tontine_introuvable':  'Tontina não encontrada',
    'connexion_requise':    'Conexão necessária',
    'verifier_connexion':   'Verifique sua conexão com a internet',
    'reessayer':            'Tentar novamente',
    'langues_disponibles':  'Idiomas disponíveis',
    'devises_associees':    'Moedas associadas',
    'appliquer':            'Aplicar',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 🇪🇸 ESPAGNOL
  // ════════════════════════════════════════════════════════════════════════════
  'es': {
    'app_nom':              'TontineClair',
    'app_slogan':           'Tus tontinas con total transparencia',
    'accueil':              'Inicio',
    'mes_tontines':         'Mis tontinas',
    'creer_tontine':        'Crear tontina',
    'rejoindre':            'Unirse',
    'rejoindre_tontine':    'Unirse a una tontina',
    'tableau_de_bord':      'Panel',
    'cotisations':          'Cuotas',
    'caisse':               'Caja',
    'prets':                'Préstamos',
    'tirage':               'Sorteo',
    'votes':                'Votos',
    'membres':              'Miembros',
    'journal':              'Diario',
    'historique':           'Historial',
    'classement':           'Clasificación',
    'abonnement':           'Suscripción',
    'parametres':           'Ajustes',
    'langue':               'Idioma',
    'choisir_langue':       'Elegir idioma',
    'langue_actuelle':      'Idioma actual',
    'langue_choisie':       'Idioma seleccionado',
    'langue_modifiee':      'Idioma cambiado correctamente',
    'enregistrer':          'Guardar',
    'annuler':              'Cancelar',
    'confirmer':            'Confirmar',
    'retour':               'Volver',
    'fermer':               'Cerrar',
    'erreur':               'Error',
    'succes':               'Éxito',
    'chargement':           'Cargando…',
    'aucune_tontine':       'Sin tontinas',
    'code_tontine':         'Código de tontina',
    'nom_tontine':          'Nombre de la tontina',
    'montant':              'Monto',
    'devise':               'Divisa',
    'periodicite':          'Periodicidad',
    'membres_count':        'miembros',
    'tour':                 'Ronda',
    'cycle':                'Ciclo',
    'beneficiaire':         'Beneficiario',
    'paye':                 'Pagado',
    'non_paye':             'No pagado',
    'total':                'Total',
    'solde':                'Saldo',
    'caisse_solde':         'Saldo de caja',
    'vote_ouvert':          'Votación abierta',
    'vote_clos':            'Votación cerrada',
    'oui':                  'Sí',
    'non':                  'No',
    'abstention':           'Abstención',
    'ont_vote':             'han votado',
    'restant':              'restante',
    'verrouille':           'Bloqueado',
    'nouveau_cycle':        'Nuevo ciclo',
    'cycle_termine':        'Ciclo completado',
    'deconnexion':          'Cerrar sesión',
    'pin':                  'PIN',
    'entrer_pin':           'Ingresa tu PIN',
    'pin_incorrect':        'PIN incorrecto',
    'gestionnaire':         'Gestor',
    'membre':               'Miembro',
    'ajouter_membre':       'Agregar miembro',
    'supprimer':            'Eliminar',
    'modifier':             'Editar',
    'details':              'Detalles',
    'partager':             'Compartir',
    'exporter_pdf':         'Exportar PDF',
    'notifications':        'Notificaciones',
    'rappels':              'Recordatorios',
    'echeance':             'Vencimiento',
    'retard':               'Atrasado',
    'dans_jours':           'en {n} días',
    'demain':               'Mañana',
    'aujourdhui':           'Hoy',
    'bienvenue':            'Bienvenido',
    'nouveau':              'Nuevo',
    'rechercher':           'Buscar',
    'tontine_introuvable':  'Tontina no encontrada',
    'connexion_requise':    'Conexión requerida',
    'verifier_connexion':   'Verifica tu conexión a internet',
    'reessayer':            'Reintentar',
    'langues_disponibles':  'Idiomas disponibles',
    'devises_associees':    'Divisas asociadas',
    'appliquer':            'Aplicar',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 🇰🇪 SWAHILI (Kiswahili)
  // ════════════════════════════════════════════════════════════════════════════
  'sw': {
    'app_nom':              'TontineClair',
    'app_slogan':           'Tontines zako kwa uwazi kamili',
    'accueil':              'Nyumbani',
    'mes_tontines':         'Tontines zangu',
    'creer_tontine':        'Unda tontine',
    'rejoindre':            'Jiunge',
    'rejoindre_tontine':    'Jiunge na tontine',
    'tableau_de_bord':      'Dashibodi',
    'cotisations':          'Michango',
    'caisse':               'Hazina',
    'prets':                'Mikopo',
    'tirage':               'Kura',
    'votes':                'Kura za maoni',
    'membres':              'Wanachama',
    'journal':              'Rekodi',
    'historique':           'Historia',
    'classement':           'Orodha',
    'abonnement':           'Usajili',
    'parametres':           'Mipangilio',
    'langue':               'Lugha',
    'choisir_langue':       'Chagua lugha',
    'langue_actuelle':      'Lugha ya sasa',
    'langue_choisie':       'Lugha iliyochaguliwa',
    'langue_modifiee':      'Lugha imebadilishwa',
    'enregistrer':          'Hifadhi',
    'annuler':              'Ghairi',
    'confirmer':            'Thibitisha',
    'retour':               'Rudi',
    'fermer':               'Funga',
    'erreur':               'Hitilafu',
    'succes':               'Mafanikio',
    'chargement':           'Inapakia…',
    'aucune_tontine':       'Hakuna tontines',
    'code_tontine':         'Msimbo wa tontine',
    'nom_tontine':          'Jina la tontine',
    'montant':              'Kiasi',
    'devise':               'Sarafu',
    'periodicite':          'Mara kwa mara',
    'membres_count':        'wanachama',
    'tour':                 'Zamu',
    'cycle':                'Mzunguko',
    'beneficiaire':         'Mfaidika',
    'paye':                 'Amelipa',
    'non_paye':             'Hajalipa',
    'total':                'Jumla',
    'solde':                'Salio',
    'caisse_solde':         'Salio ya hazina',
    'vote_ouvert':          'Kura wazi',
    'vote_clos':            'Kura imefungwa',
    'oui':                  'Ndiyo',
    'non':                  'Hapana',
    'abstention':           'Kujiepusha',
    'ont_vote':             'wamepiga kura',
    'restant':              'zilizobaki',
    'verrouille':           'Imefungwa',
    'nouveau_cycle':        'Mzunguko mpya',
    'cycle_termine':        'Mzunguko umekamilika',
    'deconnexion':          'Toka',
    'pin':                  'PIN',
    'entrer_pin':           'Ingiza PIN yako',
    'pin_incorrect':        'PIN si sahihi',
    'gestionnaire':         'Msimamizi',
    'membre':               'Mwanachama',
    'ajouter_membre':       'Ongeza mwanachama',
    'supprimer':            'Futa',
    'modifier':             'Hariri',
    'details':              'Maelezo',
    'partager':             'Shiriki',
    'exporter_pdf':         'Hamisha PDF',
    'notifications':        'Arifa',
    'rappels':              'Vikumbusha',
    'echeance':             'Tarehe ya malipo',
    'retard':               'Umechelewa',
    'dans_jours':           'katika siku {n}',
    'demain':               'Kesho',
    'aujourdhui':           'Leo',
    'bienvenue':            'Karibu',
    'nouveau':              'Mpya',
    'rechercher':           'Tafuta',
    'tontine_introuvable':  'Tontine haikupatikana',
    'connexion_requise':    'Muunganisho unahitajika',
    'verifier_connexion':   'Angalia muunganisho wako wa intaneti',
    'reessayer':            'Jaribu tena',
    'langues_disponibles':  'Lugha zinazopatikana',
    'devises_associees':    'Sarafu zinazohusika',
    'appliquer':            'Tekeleza',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 🇳🇬 HAOUSSA (Hausa)
  // ════════════════════════════════════════════════════════════════════════════
  'ha': {
    'app_nom':              'TontineClair',
    'app_slogan':           'Tontines ɗinku da cikakken gaskiya',
    'accueil':              'Gida',
    'mes_tontines':         'Tontines na',
    'creer_tontine':        'Ƙirƙiri tontine',
    'rejoindre':            'Shiga',
    'rejoindre_tontine':    'Shiga tontine',
    'tableau_de_bord':      'Dashboard',
    'cotisations':          'Gudunmawa',
    'caisse':               'Akwatin kudi',
    'prets':                'Bashi',
    'tirage':               'Zaɓe',
    'votes':                'Zaɓe',
    'membres':              'Membobbin',
    'journal':              'Rikodin',
    'historique':           'Tarihi',
    'classement':           'Matsayi',
    'abonnement':           'Kudin shiga',
    'parametres':           'Saituna',
    'langue':               'Yare',
    'choisir_langue':       'Zaɓi yare',
    'langue_actuelle':      'Yaren yanzu',
    'langue_choisie':       'Yaren da aka zaɓa',
    'langue_modifiee':      'An canza yare cikin nasara',
    'enregistrer':          'Ajiye',
    'annuler':              'Soke',
    'confirmer':            'Tabbatar',
    'retour':               'Koma',
    'fermer':               'Rufe',
    'erreur':               'Kuskure',
    'succes':               'Nasara',
    'chargement':           'Ana lodi…',
    'aucune_tontine':       'Babu tontines',
    'code_tontine':         'Lambar tontine',
    'nom_tontine':          'Sunan tontine',
    'montant':              'Adadin kudi',
    'devise':               'Kudin ƙasa',
    'periodicite':          'Lokaci zuwa lokaci',
    'membres_count':        'membobbi',
    'tour':                 'Juyi',
    'cycle':                'Zagaye',
    'beneficiaire':         'Mai amfani',
    'paye':                 'An biya',
    'non_paye':             'Ba a biya ba',
    'total':                'Jimla',
    'solde':                'Ragowar kudi',
    'caisse_solde':         'Ragowar akwatin kudi',
    'vote_ouvert':          'Zaɓe a buɗe',
    'vote_clos':            'Zaɓe ya ƙare',
    'oui':                  'Ee',
    'non':                  'A\'a',
    'abstention':           'Nisanta',
    'ont_vote':             'sun zaɓa',
    'restant':              'suka rage',
    'verrouille':           'An kulle',
    'nouveau_cycle':        'Sabon zagaye',
    'cycle_termine':        'Zagaye ya ƙare',
    'deconnexion':          'Fita',
    'pin':                  'PIN',
    'entrer_pin':           'Shigar da PIN ɗinka',
    'pin_incorrect':        'PIN ba daidai ba',
    'gestionnaire':         'Mai kula',
    'membre':               'Memba',
    'ajouter_membre':       'Ƙara memba',
    'supprimer':            'Share',
    'modifier':             'Gyara',
    'details':              'Bayani',
    'partager':             'Raba',
    'exporter_pdf':         'Fitar da PDF',
    'notifications':        'Sanarwa',
    'rappels':              'Tunatar',
    'echeance':             'Ranar biyan kudi',
    'retard':               'Ya jinkirta',
    'dans_jours':           'cikin kwanaki {n}',
    'demain':               'Gobe',
    'aujourdhui':           'Yau',
    'bienvenue':            'Barka da zuwa',
    'nouveau':              'Sabo',
    'rechercher':           'Nema',
    'tontine_introuvable':  'Ba a sami tontine ba',
    'connexion_requise':    'Ana buƙatar haɗi',
    'verifier_connexion':   'Duba haɗin internetin ka',
    'reessayer':            'Sake gwadawa',
    'langues_disponibles':  'Harsunan da ake da su',
    'devises_associees':    'Kudaden da ke da alaƙa',
    'appliquer':            'Aiwatar',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // 🇪🇹 AMHARIQUE (አማርኛ)
  // ════════════════════════════════════════════════════════════════════════════
  'am': {
    'app_nom':              'TontineClair',
    'app_slogan':           'ቶንቲኖቻችሁ በሙሉ ግልጽነት',
    'accueil':              'መነሻ',
    'mes_tontines':         'የእኔ ቶንቲኖች',
    'creer_tontine':        'ቶንቲን ፍጠር',
    'rejoindre':            'ተቀላቀል',
    'rejoindre_tontine':    'ቶንቲን ተቀላቀል',
    'tableau_de_bord':      'ዳሽቦርድ',
    'cotisations':          'አበርክቶዎች',
    'caisse':               'ግምጃ ቤት',
    'prets':                'ብድሮች',
    'tirage':               'ዕጣ',
    'votes':                'ምርጫዎች',
    'membres':              'አባላት',
    'journal':              'ማስታወሻ',
    'historique':           'ታሪክ',
    'classement':           'ደረጃ',
    'abonnement':           'ደንበኝነት',
    'parametres':           'ቅንብሮች',
    'langue':               'ቋንቋ',
    'choisir_langue':       'ቋንቋ ምረጥ',
    'langue_actuelle':      'አሁን ያለው ቋንቋ',
    'langue_choisie':       'የተመረጠ ቋንቋ',
    'langue_modifiee':      'ቋንቋ በተሳካ ሁኔታ ተቀይሯል',
    'enregistrer':          'አስቀምጥ',
    'annuler':              'ሰርዝ',
    'confirmer':            'አረጋግጥ',
    'retour':               'ተመለስ',
    'fermer':               'ዝጋ',
    'erreur':               'ስህተት',
    'succes':               'ስኬት',
    'chargement':           'እየጫነ ነው…',
    'aucune_tontine':       'ምንም ቶንቲን የለም',
    'code_tontine':         'የቶንቲን ኮድ',
    'nom_tontine':          'የቶንቲን ስም',
    'montant':              'መጠን',
    'devise':               'ምንዛሬ',
    'periodicite':          'ተደጋጋሚነት',
    'membres_count':        'አባላት',
    'tour':                 'ዙር',
    'cycle':                'ዑደት',
    'beneficiaire':         'ተጠቃሚ',
    'paye':                 'ተከፍሏል',
    'non_paye':             'አልተከፈለም',
    'total':                'ጠቅላላ',
    'solde':                'ቀሪ',
    'caisse_solde':         'የግምጃ ቤት ቀሪ',
    'vote_ouvert':          'ክፍት ምርጫ',
    'vote_clos':            'ምርጫ ተዘጋ',
    'oui':                  'አዎ',
    'non':                  'አይ',
    'abstention':           'ድምፀ ተዓቅቦ',
    'ont_vote':             'ድምፅ ሰጥተዋል',
    'restant':              'ቀሪ',
    'verrouille':           'ተቆልፏል',
    'nouveau_cycle':        'አዲስ ዑደት',
    'cycle_termine':        'ዑደቱ ተጠናቋል',
    'deconnexion':          'ውጣ',
    'pin':                  'ፒን',
    'entrer_pin':           'ፒንህን አስገባ',
    'pin_incorrect':        'ፒን ትክክል አይደለም',
    'gestionnaire':         'አስተዳዳሪ',
    'membre':               'አባል',
    'ajouter_membre':       'አባል ጨምር',
    'supprimer':            'ሰርዝ',
    'modifier':             'አርትዕ',
    'details':              'ዝርዝሮች',
    'partager':             'አጋራ',
    'exporter_pdf':         'PDF ወደ ውጭ ላክ',
    'notifications':        'ማሳወቂያዎች',
    'rappels':              'አስታዋሾች',
    'echeance':             'የመክፈያ ቀን',
    'retard':               'ዘግይቷል',
    'dans_jours':           'በ{n} ቀናት ውስጥ',
    'demain':               'ነገ',
    'aujourdhui':           'ዛሬ',
    'bienvenue':            'እንኳን ደህና መጣህ',
    'nouveau':              'አዲስ',
    'rechercher':           'ፈልግ',
    'tontine_introuvable':  'ቶንቲን አልተገኘም',
    'connexion_requise':    'ግንኙነት ያስፈልጋል',
    'verifier_connexion':   'የኢንተርኔት ግንኙነትህን ፈትሽ',
    'reessayer':            'እንደገና ሞክር',
    'langues_disponibles':  'የሚገኙ ቋንቋዎች',
    'devises_associees':    'ተያያዥ ምንዛሬዎች',
    'appliquer':            'ተግብር',
  },
};
